const CONSIGLI = [
["Il tuo terreno è argilla: la regola d'oro è non lavorarlo bagnato","Se vanghi l'argilla fradicia diventa cemento. Aspetta che una manciata si sbricioli senza attaccarsi alla mano. In autunno lascia le zolle grosse e ci pensa il gelo a spezzarle. Compost, foglie e sovescio ogni anno: l'argilla migliora piano ma migliora davvero. Le aiuole rialzate sono la scorciatoia."],
["Le gelate tardive di aprile a fondovalle sono la regola, non l'eccezione","Sei a 440 m in una valle stretta con il fiume: l'aria fredda scende di notte e si ferma lì. Le ultime gelate arrivano spesso fino al 20–25 aprile e nei brutti anni ai primi di maggio. Tutto quello che è tenero (pomodori, zucchine, basilico, fagioli) va fuori dopo il 15 maggio, punto. Se hai un pezzo di campo più in alto o su un pendio, usalo per le cose delicate."],
["Aglio e cipolle vogliono i piedi asciutti","Su argilla vicino al fiume, aglio e cipolle marciscono se piantati in piano d'autunno. Aiuola rialzata di 15–20 cm con compost, oppure pianta a fine febbraio in un terreno drenante: teste un po' più piccole, zero perdite."],
["Il tessuto non tessuto vale più di qualsiasi concime","Con un TNT da 30 g/m² spinaci, valerianella, cime di rapa e radicchi passano l'inverno all'aperto, e a marzo hai tre settimane di vantaggio. Il tunnel basso ti dà lattuga fino a dicembre. Scoprili nelle ore di sole, o arriva la muffa."],
["Volpe fuori, riccio dentro","Gli unici che ti girano intorno sono la volpe e il riccio. La volpe scava sotto la rete e viene per fragole, frutti caduti, compost e galline: rete interrata 30 cm, compost chiuso, pollaio serrato la sera. Il riccio invece è il tuo insetticida notturno: lasciagli un varco di 13 cm nella recinzione, mai lumachicidi con metaldeide, mai reti afflosciate a terra. Tutto nella pagina Costruire."],
["L'umidità del fiume porta funghi e lumache","Le nebbie mattutine bagnano le foglie: innaffia alla base, mai la sera, tieni le piante larghe. Pomodori sotto un tetto di plastica (anche solo un telo teso su pali) prendono metà della peronospora. Le lumache le togli a mano la sera dopo la pioggia; una tavola a terra la mattina è piena."],
["Le notti fresche d'estate: cosa rende e cosa no","A 440 m le notti di luglio stanno sotto i 18 °C. Melanzane, peperoni, okra, batata, meloni e angurie vogliono il posto più caldo e riparato con pacciamatura nera, e in un'estate fredda rendono poco: non farci affidamento. Rendono benissimo invece pomodori, fagioli, zucche, cavoli, insalate, radici, piselli, fave, aglio, cipolle, tutte le brassiche orientali, piccoli frutti."],
["Pacciama con quello che hai","Foglie secche, paglia, erba tagliata asciutta: 5–8 cm sopra tutto tengono le radici al caldo d'inverno, fresche d'estate, l'argilla morbida e l'acqua nel terreno. Le foglie di noce lasciale fuori. Sopra l'ala gocciolante la paglia fa durare la plastica il triplo."],
["Ruota le famiglie, non le piante","Solanacee (pomodoro, patata, peperone, melanzana), brassiche (tutti i cavoli, rape, ravanelli, orientali), legumi, cucurbitacee (zucche, cetrioli), liliacee (aglio, cipolla, porro), ombrellifere (carota, sedano, finocchio, prezzemolo). Quattro zone, ogni anno si scala di una. In dicembre aggiorni la mappa e in tre anni hai risolto metà dei problemi."],
["Semi e piante da chi coltiva in zona","Un vivaio di pianura ti vende finocchi e broccoli che qui non fanno in tempo. Chiedi sempre se la varietà è da autunno o da primavera. Le varietà locali esistono ancora: Mela Rosa dei Sibillini, cicerchia di Serra de' Conti, lenticchia di Castelluccio, fagiolo di Laverino, cece di Serra: cercale alle fiere dei semi e alle sagre, e salva i semi."],
["Le insolite: tre nuove all'anno, non trenta","Ogni anno prova tre cose che non hai mai coltivato, su una riga sola. Se rendono e ti piacciono, l'anno dopo raddoppi. Se provi venti novità insieme, l'orto diventa un giardino botanico e non mangi. Le insolite più sicure qui: zafferano, cime di rapa, orientali (mizuna, pak choi, cavolo cinese), topinambur, pastinaca, navone, rabarbaro, agretti, cicerchia, popcorn, physalis."],
["Tieni un quaderno dell'orto","Data di semina, data della prima e dell'ultima gelata, cosa è andato e cosa no, quanto hai raccolto. Il secondo anno il quaderno vale più di questo sito, perché parla del tuo campo e non di una quota generica."],
["Le lune: se ti fa piacere seguile, ma non rimandare per la luna","La tradizione vuole le semine di foglia in luna calante e quelle da frutto in crescente. Le prove serie non trovano differenze; il freddo in arrivo invece le trova eccome. Tra seminare oggi con la luna sbagliata e tra dieci giorni con quella giusta, semina oggi."],
["Compost e letame: la cura lunga","Ogni anno 3–5 cm di compost o letame maturo su tutte le aiuole in autunno, lasciato in superficie. Se hai un allevatore vicino, il letame di pecora o cavallo è il migliore per l'argilla. In cinque anni la terra dell'orto non sembra più quella del campo intorno."],
["Non esagerare il primo anno","Sei aiuole da 1,2 × 3 m curate bene rendono più di trecento metri quadri abbandonati a luglio. Cresci di un terzo ogni anno, quando l'anno prima non hai mollato niente."]
];

