const CONSIGLI = [
["Conosci la tua terra, e non lavorarla mai bagnata","Vale per tutte, ed è legge per l'argilla: vangata fradicia diventa cemento. Aspetta che una manciata si sbricioli senza attaccarsi alla mano. In autunno lascia le zolle grosse e ci pensa il gelo a spezzarle. Compost, foglie e sovescio ogni anno migliorano qualsiasi terra, piano ma davvero. Le aiuole rialzate sono la scorciatoia per chi ha terra pesante."],
["Il gelo non guarda il calendario: guarda dove sei","L'aria fredda di notte scivola in basso e si ferma nei fondovalle e vicino ai corsi d'acqua: lì le gelate tardive arrivano settimane dopo che sui pendii sono finite. Impara le date del TUO orto (il quaderno serve a questo) e tieni un telo pronto per le piante tenere. Se hai un pezzo di terreno in pendio, usalo per le cose delicate: il freddo non si ferma dove scorre."],
["Aglio e cipolle vogliono i piedi asciutti","In qualsiasi terra che ristagna d'inverno, aglio e cipolle piantati in piano d'autunno marciscono. Aiuola rialzata di 15–20 cm, oppure impianto a fine inverno in terreno drenante: teste un po' più piccole, zero perdite."],
["Il tessuto non tessuto vale più di qualsiasi concime","Con un TNT da 30 g/m² spinaci, valerianella, cime di rapa e radicchi passano l'inverno all'aperto, e a fine inverno hai tre settimane di vantaggio. Il tunnel basso regala insalata anche nei mesi freddi. Scoprili nelle ore di sole, o arriva la muffa."],
["Volpe fuori, riccio dentro","La volpe scava sotto la rete e viene per fragole, frutti caduti, compost e galline: rete interrata 30 cm, compost chiuso, pollaio serrato la sera. Il riccio invece è l'insetticida notturno dell'orto: lasciagli un varco di 13 cm nella recinzione, mai lumachicidi con metaldeide, mai reti afflosciate a terra. Tutto nella pagina Costruire."],
["Aria umida, foglie asciutte","Se il tuo orto sta in un fondovalle, vicino all'acqua o dove le nebbie sono di casa, i funghi sono il nemico numero uno: innaffia alla base, mai la sera, tieni le piante larghe. I pomodori sotto un tetto di plastica (anche solo un telo teso su pali) prendono metà della peronospora. Le lumache si tolgono a mano la sera dopo la pioggia; una tavola appoggiata a terra la mattina è piena."],
["Notti fresche o notti calde: cosa rende da te","Dove le notti d'estate restano sotto i 18 °C (collina, montagna, valli), melanzane, peperoni, okra, batata, meloni e angurie vogliono il posto più caldo con pacciamatura nera, e nelle estati fredde rendono poco. Dove le notti sono calde è il contrario: insalate, piselli e spinaci d'estate soffrono, e si spostano a mezz'ombra o alle mezze stagioni. L'orto buono asseconda il suo clima, non lo combatte."],
["Pacciama con quello che hai","Foglie secche, paglia, erba tagliata asciutta: 5–8 cm sopra tutto tengono le radici al caldo d'inverno, fresche d'estate, la terra morbida e l'acqua nel terreno. Le foglie di noce lasciale fuori. Sopra l'ala gocciolante la paglia fa durare la plastica il triplo."],
["Ruota le famiglie, non le piante","Solanacee (pomodoro, patata, peperone, melanzana), brassiche (tutti i cavoli, rape, ravanelli, orientali), legumi, cucurbitacee (zucche, cetrioli), liliacee (aglio, cipolla, porro), ombrellifere (carota, sedano, finocchio, prezzemolo). Quattro zone, ogni anno si scala di una. In dicembre aggiorni la mappa e in tre anni hai risolto metà dei problemi."],
["Semi e piante da chi coltiva vicino a te","Un vivaio di pianura vende finocchi e broccoli che in montagna non fanno in tempo, e viceversa. Chiedi sempre se la varietà è da autunno o da primavera. E ogni territorio ha ancora le sue varietà locali — mele antiche, legumi di paese, ortaggi col nome di un borgo: cercale alle fiere dei semi e alle sagre della tua zona, e salva i semi."],
["Le insolite: tre nuove all'anno, non trenta","Ogni anno prova tre cose che non hai mai coltivato, su una riga sola. Se rendono e ti piacciono, l'anno dopo raddoppi. Se provi venti novità insieme, l'orto diventa un giardino botanico e non mangi. Le più sicure per cominciare: zafferano, cime di rapa, orientali (mizuna, pak choi, cavolo cinese), topinambur, pastinaca, rabarbaro, agretti, popcorn, physalis."],
["Tieni un quaderno dell'orto","Data di semina, data della prima e dell'ultima gelata, cosa è andato e cosa no, quanto hai raccolto. Il secondo anno il quaderno vale più di questo sito, perché parla del tuo campo esatto e non del tuo comune in generale."],
["Le lune: se ti fa piacere seguile, ma non rimandare per la luna","La tradizione vuole le semine di foglia in luna calante e quelle da frutto in crescente. Le prove serie non trovano differenze; il freddo in arrivo invece le trova eccome. Tra seminare oggi con la luna sbagliata e tra dieci giorni con quella giusta, semina oggi."],
["Compost e letame: la cura lunga","Ogni anno 3–5 cm di compost o letame maturo su tutte le aiuole in autunno, lasciato in superficie. Se hai un allevatore vicino, il letame di pecora o di cavallo è il migliore per le terre pesanti. In cinque anni la terra dell'orto non sembra più quella del campo intorno."],
["Non esagerare il primo anno","Sei aiuole da 1,2 × 3 m curate bene rendono più di trecento metri quadri abbandonati a luglio. Cresci di un terzo ogni anno, quando l'anno prima non hai mollato niente."]
];
