const MESI = [
{ id:"gennaio", nome:"Gennaio", sotto:"Il mese della carta e del semenzaio. Fuori si raccoglie e si pota; dentro casa parte già l'estate.",
  clima:"Minime −5/−8 °C nelle notti serene, neve possibile. Terreno gelato o fradicio: non si lavora.",
  piante:[
    ["Peperoni e peperoncini","semenzaio","Da metà mese in casa al caldo (24–26 °C): sono lentissimi, ci mettono 3 settimane a nascere e 3 mesi a diventare piantine.",0],
    ["Melanzane","semenzaio","Ultima decade, stesse esigenze dei peperoni.",0],
    ["Cipolla da seme","semenzaio","In cassetta fresca (15 °C): piantine da trapiantare a fine marzo. Le varietà da conservazione (dorata, ramata) rendono più dei bulbilli.",0],
    ["Porro","semenzaio","Semina fitta in cassetta, trapianto a maggio, raccolta da ottobre a marzo.",0],
    ["Sedano e sedano rapa","semenzaio","Semi minuscoli in superficie, luce per germinare. Il sedano rapa è la radice dell'inverno.",0],
    ["Rocoto (peperoncino andino)","semenzaio","Insolito: peperoncino perenne a fiori viola che tollera il fresco meglio di tutti gli altri. Da tenere in vaso e ritirare d'inverno.",1],
    ["Physalis (alchechengi peruviano)","semenzaio","Insolito: bacche dolci-acide in lanterna, come un pomodorino di montagna. Semina ora, trapianto a maggio.",1],
    ["Germogli e microgreens","semina","In cucina, in vaschetta: piselli, girasole, ravanello, crescione. Pronti in 7–10 giorni, l'unica cosa fresca di gennaio.",0],
    ["Cicoria di Bruxelles (witloof), forzatura","impianto","Insolito: le radici raccolte in autunno messe in un secchio di sabbia al buio in cantina danno i cespi bianchi in 3–4 settimane.",1],
    ["Rabarbaro, forzatura","impianto","Insolito: copri la corona con un secchio nero capovolto: a marzo hai coste rosa dolcissime, prima di tutti.",1],
    ["Fave e piselli","tunnel","Fine mese, solo sotto tunnel e su aiuola rialzata. All'aperto aspetta fine febbraio.",0],
    ["Alberi da frutto a radice nuda","impianto","Solo nelle giornate senza gelo e a terreno non fradicio. Altrimenti mettili in una buca temporanea (\"tallonatura\") e piantali a febbraio-marzo.",0]
  ],
  raccolta:"Cavolo nero, verza, cavolini di Bruxelles, porri, spinaci e valerianella sotto TNT, radicchio, topinambur e pastinaca (si scavano al bisogno), cavolo rapa, catalogna.",
  lavori:[
    "Disegna l'orto sulla carta con le rotazioni: dove c'erano pomodori e patate quest'anno vanno cavoli o legumi",
    "Fai l'inventario dei semi: quelli vecchi di 3+ anni (cipolla, porro, prezzemolo, pastinaca) buttali, non nascono",
    "Ordina i semi e le patate da seme: le varietà buone finiscono entro febbraio",
    "Pota meli, peri, viti e piccoli frutti nelle giornate asciutte sopra lo zero (non il ciliegio, non l'albicocco)",
    "Costruisci: aiuole rialzate, cassone freddo, cassette nido (le cince cercano casa a febbraio)",
    "Pulisci e disinfetta vasetti e cassette da semina con acqua calda e aceto",
    "Scuoti la neve dal tunnel; nelle giornate di sole scoprilo un'ora per far uscire l'umidità",
    "Affila e ungi gli attrezzi, sistema i manici",
    "Se hai la cisterna, svuota tubi e rubinetti per il gelo"
  ] },

{ id:"febbraio", nome:"Febbraio", sotto:"Il freddo continua ma la luce torna: parte il grosso del semenzaio e, sotto protezione, le prime semine in terra.",
  clima:"Ancora gelate forti (−5 °C frequenti), ma di giorno il sole scalda tunnel e cassone. Ultima settimana spesso mite.",
  piante:[
    ["Pomodori","semenzaio","Dal 20 in poi in casa al caldo. Prima è inutile: le piantine invecchiano prima del trapianto di metà maggio.",0],
    ["Peperoni, peperoncini, melanzane","semenzaio","Se non l'hai fatto a gennaio, adesso: è l'ultima chiamata utile.",0],
    ["Lattughe, cavolo cappuccio precoce, broccolo","semenzaio","In cassetta nel cassone freddo o sul davanzale: trapianto a fine marzo sotto TNT.",0],
    ["Cipolla, porro, sedano","semenzaio","Come a gennaio, ancora in tempo.",0],
    ["Tagete, calendula, nasturzio, borragine","semenzaio","I fiori che proteggono l'orto: tagete contro i nematodi, calendula e borragine per le api, nasturzio come esca per gli afidi.",0],
    ["Fave","semina","Fine mese all'aperto, 5 cm di profondità, sotto TNT. Reggono −5 °C.",0],
    ["Piselli e taccole","semina","Fine mese, varietà a grano liscio (più rustiche). Rete o rami per farli salire.",0],
    ["Spinacio","semina","Sotto TNT a fine mese: raccolta ad aprile-maggio prima che fiorisca.",0],
    ["Aglio","impianto","Se non l'hai messo in autunno: fine febbraio, su aiuola rialzata. Teste un po' più piccole ma nessun rischio di marciume.",0],
    ["Cipolla da bulbillo e scalogno","impianto","Fine mese, 2 cm sotto, 15 cm tra uno e l'altro.",0],
    ["Lattuga, rucola, ravanelli, valerianella, carote precoci","tunnel","Sotto tunnel basso o nel cassone freddo, a fine mese.",0],
    ["Agretti (barba di frate)","semina","Insolito: i semi durano pochi mesi, compra quelli dell'anno. Semina fitta a fine febbraio–marzo: nascono male, ma poi da fine aprile li tagli e ricrescono.",1],
    ["Asparagi (zampe)","impianto","Insolito ma perfetto qui: fossa 30 cm con compost, zampe di 1 anno a 40 cm. Raccolta dal terzo anno, poi per 15 anni.",1],
    ["Rabarbaro (rizomi)","impianto","Insolito: fine febbraio–marzo, in un angolo umido e fresco. Ama l'argilla e il freddo: da noi sta benissimo.",1],
    ["Topinambur (tuberi)","impianto","Insolito: pianta i tuberi a 10 cm in un angolo che non ti serve più, perché non se ne andrà mai. Raccolta da novembre a marzo scavando al bisogno.",1],
    ["Luppolo (rizomi)","impianto","Insolito: perenne rampicante da 6 m, per la birra fatta in casa e i germogli (\"asparagi di luppolo\") da mangiare a marzo.",1],
    ["Alberi da frutto, lamponi, ribes, uva spina","impianto","Tutto il mese, terreno permettendo. Mirtillo solo in vaso grande con terriccio acido: l'argilla lo ammazza.",0]
  ],
  raccolta:"Cavolo nero, verza, cavolini, porri, topinambur, pastinaca, spinaci e valerianella del tunnel, i primi germogli di luppolo a fine mese se è mite.",
  lavori:[
    "Finisci le potature: alberi da frutto, lamponi (taglia a terra i tralci che hanno fruttato), ribes",
    "Distribuisci letame maturo o compost sulle aiuole e lascialo in superficie: non vangare l'argilla bagnata",
    "Monta tunnel bassi e cassone freddo: da fine mese sono già utili",
    "Prepara il letto caldo con letame fresco se hai il cassone",
    "Trattamento con rame o poltiglia bordolese sugli alberi da frutto prima del rigonfiamento delle gemme",
    "Togli la pacciamatura vecchia dalle fragole e pulisci le foglie secche",
    "Appendi le cassette nido entro metà mese",
    "Controlla la recinzione: chiudi i buchi scavati dalla volpe sotto la rete e lascia il passaggio da 13 cm per il riccio",
    "Metti a germogliare le patate precoci in cassetta alla luce e al fresco (pregermogliazione)"
  ] },

{ id:"marzo", nome:"Marzo", sotto:"Il mese in cui l'orto si riapre davvero. Si semina di tutto sotto protezione e le rustiche vanno in campo.",
  clima:"Gelate notturne ancora normali (−2/−4 °C), giornate anche a 18 °C. Terreno lavorabile dalla seconda metà, se non piove troppo.",
  piante:[
    ["Pomodori","semenzaio","Se non l'hai fatto a fine febbraio. Le varietà: cuore di bue, costoluto fiorentino, San Marzano, ciliegino nero e un tardivo da conserva.",0],
    ["Basilico","semenzaio","Fine mese, al caldo. Fuori solo da metà maggio.",0],
    ["Zucchine, zucche, cetrioli, meloni","semenzaio","Ultima decade in vasetti singoli: nascono in una settimana, non seminarli prima o diventano ingestibili.",0],
    ["Cavoli estivi, lattughe, sedano, porri, cipolla","semenzaio","In cassone o sul davanzale.",0],
    ["Cardo","semenzaio","Insolito: come un carciofo di cui mangi le coste. Semina in vasetti, trapianto a maggio, raccolta a novembre dopo l'imbianchimento (lo avvolgi in cartone per 3 settimane).",1],
    ["Stevia","semenzaio","Insolito: dolcificante naturale, perenne in vaso da ritirare d'inverno. Semi capricciosi: compra 2–3 piantine, poi si moltiplica per talea.",1],
    ["Tomatillo","semenzaio","Insolito: il pomodoro verde messicano della salsa verde. Cresce come un pomodoro, ne servono almeno due piante per impollinarsi.",1],
    ["Patate precoci","impianto","Fine mese sotto TNT, tuberi pregermogliati a 10 cm, file a 70 cm. Le tardive ad aprile.",0],
    ["Cipolla (piantine e bulbilli), scalogno, aglio","impianto","Tutto il mese: ultima chiamata per l'aglio.",0],
    ["Fave, piselli, taccole","semina","Tutto il mese all'aperto.",0],
    ["Spinacio, bietola da costa, bietola da orto","semina","Semina diretta.",0],
    ["Carote","semina","Fine mese, mescolando il seme con la sabbia. Nell'argilla scegli varietà corte (Chantenay, Parigina): le lunghe si biforcano.",0],
    ["Ravanelli, rucola, lattughe da taglio, cicoria da taglio","semina","Semina diretta scaglionata ogni 2 settimane.",0],
    ["Prezzemolo, cerfoglio, erba cipollina","semina","Il prezzemolo ci mette 3 settimane a nascere: tieni bagnato.",0],
    ["Scorzonera e scorzobianca","semina","Insolito: radici dell'inverno dal sapore di asparago e nocciola. Semina fine marzo–aprile, raccolta da novembre.",1],
    ["Cicerchia","semina","Insolito e locale (quella di Serra de' Conti è presidio): legume durissimo che cresce nell'argilla dove il cece fallisce. Semina marzo, raccolta luglio.",1],
    ["Lenticchia","semina","Insolito: come a Castelluccio, che è qui vicino. Semina fine marzo, non concimare, raccolta a luglio. Resa piccola, soddisfazione enorme.",1],
    ["Crosne (tuberina del Giappone)","impianto","Insolito: tuberi bianchi a spirale dal sapore di carciofo. Pianta a 8 cm a marzo–aprile, raccolta a novembre.",1],
    ["Liquirizia","impianto","Insolito: rizomi a marzo in un posto profondo e caldo. Radici da raccogliere dal terzo anno.",1],
    ["Levistico (sedano di monte)","impianto","Insolito: perenne gigante, sa di sedano e dado. Una pianta basta per la famiglia. Da piantina o divisione.",1],
    ["Aromatiche perenni: salvia, rosmarino, timo, origano, menta","impianto","Piantine o divisioni. La menta in vaso interrato o invade tutto.",0],
    ["Cavolo rapa, cavolo cappuccio precoce, lattughe","trapianto","Fine mese, piantine sotto TNT.",0],
    ["Fragole","impianto","Ultima finestra utile di primavera, con piantine in vaso.",0],
    ["Kiwi, vite, fico, goji, aronia","impianto","Insolito il goji (bacche, rustico, ama i terreni difficili) e l'aronia (bacche nere antiossidanti, resiste a −30 °C). Il kiwi vuole un maschio ogni 5 femmine e una pergola solida.",1],
    ["Sovescio primaverile (favino, senape)","semina","Sulle aiuole che pianti solo a giugno: 2 mesi di copertura poi lo tagli e lo interri.",0]
  ],
  raccolta:"Ultimi cavoli, porri, spinaci, valerianella, cicoria, i primi ravanelli e lattughe del tunnel, germogli di luppolo, coste di rabarbaro forzato.",
  lavori:[
    "Prepara le aiuole: vanga solo se il terreno si sbriciola in mano, altrimenti aspetta",
    "Traccia aiuole fisse da 1,2 m con passaggi da 40 cm: non le calpesterai più",
    "Monta e prova l'impianto a goccia prima che serva davvero",
    "Metti i tutori dove andranno pomodori e fagioli finché il terreno è morbido",
    "Trapianti e semine sotto TNT: tienilo sempre a portata di mano fino a maggio",
    "Zappetta ogni settimana tra le file: le erbacce di marzo si tolgono con un dito, quelle di maggio con la zappa",
    "Inizia la lotta alle lumache: trappole di birra, tavole a terra da rovesciare la mattina, fosfato ferrico se serve",
    "Pota rosmarino, salvia, lavanda e le aromatiche legnose",
    "Innesta gli alberi da frutto (a spacco, a fine mese) se vuoi provare"
  ] },

{ id:"aprile", nome:"Aprile", sotto:"Semine dirette a raffica e nervi saldi: la gelata tardiva di metà aprile a fondovalle è quasi una regola.",
  clima:"Le ultime gelate arrivano di solito tra il 10 e il 25 aprile; nel fondovalle vicino al fiume anche ai primi di maggio. Piogge frequenti.",
  piante:[
    ["Patate (tutte)","impianto","Tutto il mese. Varietà: una precoce, una da conservazione, e per curiosità una viola (Vitelotte) o una Kennebec per la resa.",0],
    ["Carote, barbabietole, bietole, spinaci, rapa, rucola, ravanelli, lattughe","semina","Semina diretta scaglionata.",0],
    ["Pastinaca","semina","Insolito: la \"carota bianca\" medievale, dolce dopo le gelate. Semi freschi dell'anno, nascono in 3 settimane. Raccolta da novembre a marzo.",1],
    ["Cime di rapa primaverili, cavolo cinese primaverile","semina","Varietà da primavera, altrimenti fioriscono. Le vere cime di rapa sono da agosto.",0],
    ["Prezzemolo, aneto, coriandolo, cerfoglio, borragine","semina","Il coriandolo va seminato ogni 3 settimane: sale a seme subito.",0],
    ["Calendula, nasturzio, fiordaliso, cosmos, girasole","semina","Fiori commestibili e utili: fine mese direttamente in terra.",0],
    ["Mais dolce e mais da popcorn","semina","Fine mese sotto TNT. Insolito il popcorn (Glass Gem, coloratissimo): stessa coltivazione del mais. Blocchi di 4 × 4 file, non righe singole, o non si impollina.",1],
    ["Quinoa","semina","Insolito: cresce come un amaranto, 1,5 m, semi a settembre. Semina diretta a fine aprile, varietà da climi freschi.",1],
    ["Amaranto da granella e da foglia","semina","Insolito: le foglie si mangiano come spinaci, i semi si soffiano in padella. Fine aprile.",1],
    ["Fagioli e fagiolini","semina","Solo ultima settimana e sotto TNT: il seme marcisce a terreno freddo. Meglio maggio.",0],
    ["Zucchine, zucche, cetrioli, meloni, angurie","semenzaio","In vasetti al caldo per trapiantare a metà maggio; oppure semina diretta a maggio.",0],
    ["Basilico, okra, luffa, lagenaria, cucamelon","semenzaio","Al caldo. Insoliti: l'okra (vuole caldo, sceglilo solo se hai un angolo riparato a sud), la luffa (la spugna vegetale: cresce come una zucca rampicante), la lagenaria (zucca da fiasco, per ornamenti e mestoli), il cucamelon (cetriolini grandi come chicchi d'uva, sapore di lime).",1],
    ["Fagiolo di Spagna, fagiolo asparago","semenzaio","Fine mese in vasetti. Insolito il fagiolo asparago (baccelli da 50 cm, vuole caldo).",1],
    ["Cavoli estivi, lattughe, sedano, sedano rapa, porri, cardo, cavolo rapa","trapianto","Piantine dal semenzaio, con TNT nelle notti fredde.",0],
    ["Cipolle da piantina","trapianto","Se non le hai messe a marzo.",0],
    ["Rabarbaro, asparagi, topinambur, crosne, luppolo","impianto","Ultima finestra per le perenni da tubero e rizoma.",0],
    ["Fichi, melograno nano, kiwi, vite","impianto","Il melograno a 440 m con inverni a −8 è al limite: varietà russe rustiche (Salavatski) in posizione riparata, o in vaso.",1],
    ["Fragole di bosco e fragole rifiorenti","impianto","Le fragoline in un angolo a mezz'ombra: si spargono da sole.",0]
  ],
  raccolta:"Spinaci, ravanelli, lattughe, rucola, cicorie, agretti (dal 20 in poi), asparagi dal terzo anno, rabarbaro, cipollotti, erbe fresche, i primi piselli a fine mese se seminati a febbraio sotto tunnel.",
  lavori:[
    "Guarda le previsioni ogni sera: sotto i 3 °C copri tutto quello che è tenero con il TNT",
    "Pacciama patate e fave con paglia appena sono alte 15 cm",
    "Dirada carote, ravanelli e bietole seminate fitte: senza spazio non crescono",
    "Rincalza le patate quando i germogli sono a 20 cm",
    "Cima le fave quando compaiono i primi afidi neri in punta (e mangiati le punte cotte)",
    "Metti reti e tutori per piselli e taccole",
    "Avvia l'irrigazione a goccia se aprile è secco",
    "Lumache: continua ogni sera dopo la pioggia, è il mese peggiore",
    "Tieni pronte le piantine in cassone di giorno e dentro di notte: l'indurimento prima del trapianto",
    "Semina il sovescio estivo (grano saraceno) dove non pianti fino a luglio"
  ] },

{ id:"maggio", nome:"Maggio", sotto:"Dopo il 15, via ai trapianti dell'estate: pomodori, peperoni, melanzane, zucche. È il mese in cui l'orto prende forma.",
  clima:"Rischio gelata fino al 5–10 maggio a fondovalle, poi via libera. Piogge abbondanti, poi caldo verso fine mese.",
  piante:[
    ["Pomodori","trapianto","Dal 15, a 50 cm sulla fila, 40 cm di profondità (interra parte del fusto: fa radici). Con tutori già piantati.",0],
    ["Peperoni, peperoncini, melanzane","trapianto","Dal 15–20, nel posto più caldo e riparato dell'orto. Melanzana bianca o violetta lunga di Napoli per cambiare.",0],
    ["Zucchine, zucche, cetrioli, meloni, angurie","trapianto","Dal 15. Zucche: una Delica, una Butternut, una Hokkaido, e per curiosità la zucca spaghetti. Melone e anguria nella zona più assolata, con pacciamatura nera.",0],
    ["Basilico","trapianto","Dal 15, vicino ai pomodori.",0],
    ["Sedano, sedano rapa, porri, cavoli estivi, cardo","trapianto","Dal semenzaio.",0],
    ["Fagioli rampicanti e nani, fagiolini, borlotti, fagiolo di Spagna","semina","Tutto il mese, 3 semi per buca. I borlotti secchi da conservare: seminali entro fine mese.",0],
    ["Ceci","semina","Insolito da noi: vuole terreno drenato e secco, quindi aiuola rialzata. Semina inizio maggio, raccolta agosto. Resa bassa, gusto nettamente migliore del comprato.",1],
    ["Edamame (soia da mangiare fresca)","semina","Insolito: come i fagioli, varietà da orto (non industriale). Si raccolgono i baccelli verdi e si lessano con il sale.",1],
    ["Mais dolce, popcorn, girasole","semina","A blocchi. Il girasole gigante lungo la recinzione fa ombra alle insalate d'estate.",0],
    ["Carote, barbabietole, bietole, rucola, lattughe estive, ravanelli","semina","Continua le semine scaglionate. Lattughe: varietà da estate (Canasta, Regina dei ghiacci) che non salgono a seme.",0],
    ["Okra, luffa, lagenaria, cucamelon, fagiolo asparago","trapianto","Insoliti, dal semenzaio, dopo il 20 nel posto più caldo.",1],
    ["Physalis e tomatillo","trapianto","Insoliti, dal semenzaio di gennaio–marzo. Il physalis cresce a cespuglio da 1 m: dagli spazio.",1],
    ["Batata (patata dolce)","impianto","Insolito: talee radicate (si fanno in casa da un tubero in un bicchiere d'acqua da marzo). Trapianto a fine maggio su cumulo con pacciamatura nera. A 440 m ce la fa nelle estati calde.",1],
    ["Yacon","impianto","Insolito: tubero sudamericano dolce e croccante, si mangia crudo come una mela. Da pianta in vaso, trapianto dopo il 20, raccolta a ottobre prima del gelo.",1],
    ["Stevia, verbena odorosa, dragoncello francese, santoreggia, cumino dei prati","impianto","Aromatiche da piantina. La verbena odorosa (cedrina) per la tisana più buona che c'è. Il dragoncello francese solo da talea, quello da seme è russo e non sa di niente.",1],
    ["Tagete, zinnia, cosmos, nasturzio, calendula","trapianto","Tra le verdure, non in un angolo a parte: attirano gli impollinatori dove servono.",0],
    ["Zucchine e cetrioli (seconda semina)","semina","Fine mese in semina diretta: entreranno in produzione quando le prime calano.",0]
  ],
  raccolta:"Fave, piselli, taccole, lattughe, spinaci, ravanelli, agretti, asparagi, cipollotti, aglio fresco (aglione da mangiare verde), fragole a fine mese, rabarbaro, erbe aromatiche.",
  lavori:[
    "Trapianta tutto dopo il 15, la sera o con il cielo coperto, e bagna subito",
    "Lega i pomodori al tutore ogni 25 cm di crescita e togli le femminelle (i getti tra fusto e foglia) ogni settimana",
    "Pacciama tutto con paglia appena il terreno è caldo: da giugno in poi non vorrai zappare",
    "Rincalza patate e fagioli; cima le fave",
    "Controlla la dorifora sulle patate: raccogli a mano adulti e larve arancioni sotto le foglie",
    "Irrigazione a goccia: parti con 30 minuti ogni 2–3 giorni al mattino",
    "Sistema le reti per cetrioli e fagioli rampicanti e i tepee per le zucche rampicanti",
    "Semina fiori tra le file: tagete vicino ai pomodori, nasturzio vicino a zucchine e fagioli",
    "Diserba le aiuole prima della pacciamatura: una volta sola, bene"
  ] },

{ id:"giugno", nome:"Giugno", sotto:"Le estive crescono a vista d'occhio. Si raccolgono i primi frutti e si preparano già le piantine dell'autunno.",
  clima:"Notti fresche (10–12 °C) ancora nella prima metà, poi caldo. Temporali pomeridiani frequenti sui Sibillini.",
  piante:[
    ["Fagioli nani e rampicanti, fagiolini","semina","Fino a metà luglio, ogni 3 settimane per averli sempre teneri.",0],
    ["Zucchine, cetrioli","semina","Seconda o terza ondata in semina diretta.",0],
    ["Carote per l'autunno-inverno","semina","Fine giugno–metà luglio: le carote più dolci sono quelle che maturano con il freddo. Varietà Flakkee o Berlicum.",0],
    ["Barbabietole, bietole, rucola (a mezz'ombra), lattughe estive","semina","Continua a scaglionare.",0],
    ["Cavolfiore, broccolo, cavolo nero, verza, cavolini di Bruxelles, cappuccio da inverno","semenzaio","Semina in cassetta all'ombra da metà giugno: sono le piantine che trapianti a luglio–agosto per l'autunno.",0],
    ["Finocchio","semina","Fine mese in semenzaio o diretto: varietà da autunno (Romanesco, Montebianco). Trapianto a luglio–agosto.",0],
    ["Radicchio rosso da inverno, cicoria pan di zucchero, catalogna, puntarelle","semina","Fine mese in semenzaio. Insolite le puntarelle (cicoria catalogna a getti, da mangiare crude con acciughe) a queste quote: ci stanno benissimo.",1],
    ["Porri","trapianto","Piantine grosse come una matita, in solchi profondi 15 cm: si interrano man mano per imbianchirli.",0],
    ["Sedano","trapianto","Ultima finestra.",0],
    ["Grano saraceno","semina","Insolito: pianta velocissima (70 giorni), fiori bianchi che le api adorano, semi da macinare o fare bollire come cereale. Anche solo come sovescio è il migliore per l'argilla.",1],
    ["Mais tardivo, girasoli","semina","Entro il 15.",0],
    ["Melanzane e peperoni (ultimo trapianto)","trapianto","Entro il 10, poi non fanno in tempo.",0],
    ["Okra, batata, fagiolo asparago","trapianto","Entro il 10 se non l'hai fatto a maggio.",1],
    ["Fagiolo dall'occhio","semina","Insolito: legume africano che ama il caldo e i terreni poveri, non vuole acqua. Semina giugno, raccolta settembre. In Marche c'è tradizione.",1],
    ["Basilico (seconda semina)","semina","Diretto, per averlo fino a settembre.",0],
    ["Cetriolo armeno (carosello, barattiere)","semina","Insolito: i \"cetrioli\" pugliesi che in realtà sono meloni immaturi: croccanti, digeribili, senza semi. Semina diretta, come i cetrioli.",1]
  ],
  raccolta:"Fave e piselli (finiscono), aglio a fine mese (quando le foglie ingialliscono per metà), cipolle precoci, patate precoci, zucchine, lattughe, bietole, carote, barbabietole, fragole, lamponi precoci, ciliegie, primi cetrioli e fagiolini, agretti ultimi, fiori di zucchina, erbe da essiccare.",
  lavori:[
    "Raccogli l'aglio a fine mese, lascialo una settimana al sole poi all'ombra ventilata, e intreccialo",
    "Pacciama quello che non hai ancora pacciamato: da ora in poi la paglia vale più dell'acqua",
    "Sfemminella e lega i pomodori ogni settimana; a fine mese togli le foglie basse sotto il primo palco",
    "Oidio su zucchine e cetrioli: bicarbonato di sodio (5 g/l) o zolfo ogni 10 giorni, la mattina",
    "Peronospora sui pomodori dopo i temporali: rame appena si asciugano le foglie, oppure tetto di plastica sopra la fila",
    "Dorifora: passa ogni 2 giorni",
    "Cima i fagioli rampicanti quando arrivano in cima al tutore",
    "Raccogli zucchine ogni 2 giorni: se ne lasci una gigante la pianta smette",
    "Essicca le erbe (origano, timo, salvia, menta) prima della fioritura, in mazzi all'ombra o nell'essiccatoio",
    "Salva i semi delle fave e dei piselli migliori"
  ] },
{ id:"luglio", nome:"Luglio", sotto:"Raccolta a pieno ritmo e, con una mano, si semina l'orto d'autunno. Chi semina a luglio mangia a novembre.",
  clima:"Il mese più caldo (30–33 °C), ma le notti restano sotto i 18 °C: le melanzane qui fanno più fatica che a Macerata.",
  piante:[
    ["Cavolfiore, broccolo, cavolo nero, verza, cavolini di Bruxelles, cappuccio","trapianto","Da metà mese, le piantine del semenzaio di giugno. Ombreggia e bagna per una settimana.",0],
    ["Finocchio","trapianto","Da metà mese a inizio agosto: piantine a 25 cm. Rincalzare a settembre per il grumolo bianco.",0],
    ["Radicchio rosso, pan di zucchero, catalogna, puntarelle, scarola, indivia riccia","trapianto","Da fine luglio. Insolito da noi il radicchio tardivo di Treviso: le sue radici raccolte a novembre si forzano in cantina per averlo a dicembre.",1],
    ["Porri","trapianto","Ultima finestra per i porri da inverno.",0],
    ["Carote per l'inverno","semina","Entro il 15–20. Mantieni bagnato con un cartone sopra la fila finché non nascono.",0],
    ["Rapa, navone (rutabaga), ravanelli","semina","Insolito il navone: radice svedese da purè, dolce dopo il gelo, quasi inattaccabile dal freddo. Semina luglio, raccolta da novembre.",1],
    ["Daikon e ravanello nero d'inverno","semina","Fine luglio–agosto. Insoliti: il daikon (radice bianca lunga, sottaceto o cruda) e il ravanello nero (piccante, si conserva in cantina fino a marzo).",1],
    ["Bietola da costa, spinacio d'estate (Nuova Zelanda), lattughe in ombra","semina","Il tetragonio (spinacio di Nuova Zelanda) è insolito: unico \"spinacio\" che regge il caldo, si taglia tutta l'estate.",1],
    ["Fagioli nani e fagiolini (ultima semina)","semina","Entro il 15: raccolta a fine settembre.",0],
    ["Zucchine (ultima semina)","semina","Entro il 10, per averle fino alla prima gelata.",0],
    ["Prezzemolo, cerfoglio, aneto, coriandolo","semina","In ombra parziale. Il prezzemolo seminato ora sverna e produce da marzo.",0],
    ["Rucola, valerianella (tardi), cicoria da taglio","semina","Fine mese, in ombra parziale.",0],
    ["Grano saraceno (sovescio o granella)","semina","Sulle aiuole liberate dall'aglio e dalle patate precoci.",0],
    ["Fragole (stoloni)","impianto","Fine mese: metti a radicare gli stoloni in vasetti attaccati alla pianta madre, li stacchi a settembre.",0]
  ],
  raccolta:"Pomodori dai primi (fine mese), zucchine, cetrioli, fagiolini, fagioli freschi, patate, cipolle (quando il gambo si piega), aglio, carote, barbabietole, bietole, lattughe, basilico, lamponi, more, albicocche e susine precoci, cicerchia e lenticchia secche, primi peperoni verdi, fiori di zucchina, mais dolce a fine mese.",
  lavori:[
    "Raccogli cipolle e scalogni quando il gambo si piega: lasciali 4–5 giorni a terra al sole se non piove",
    "Patate: scava quando la parte aerea è secca, lascia asciugare 2 ore all'ombra, conserva al buio e al fresco",
    "Irriga alla base la mattina presto, mai le foglie, mai la sera (peronospora e lumache)",
    "Cima i pomodori indeterminati a 6–7 palchi: da ora in poi i fiori nuovi non maturano in tempo",
    "Ombreggia insalate e semenzai con rete ombreggiante o TNT leggero tra le 11 e le 17",
    "Raccogli zucchine, cetrioli e fagiolini ogni 2 giorni",
    "Pomodori: togli le foglie sotto i grappoli maturi per far girare l'aria",
    "Salva i semi di pomodoro (fermentazione 3 giorni in un bicchiere), fave, piselli, lattuga",
    "Prepara le aiuole per i trapianti d'autunno: taglia il sovescio, compost, bagna il giorno prima",
    "Controlla la cimice asiatica sui pomodori e sui frutti: raccogli e affoga la mattina presto quando è lenta"
  ] },

{ id:"agosto", nome:"Agosto", sotto:"Conserve di giorno, semine la sera. È l'ultimo mese buono per mettere a dimora quasi tutto l'orto invernale.",
  clima:"Caldo fino al 20, poi le prime notti fresche. Temporali violenti: proteggi i pomodori dalla grandine se puoi.",
  piante:[
    ["Zafferano (bulbi)","impianto","Insolito ma di casa (Sibillini e Cascia sono vicini): bulbi a 10–15 cm di profondità, 10 cm tra loro, in aiuola rialzata drenante. Fiorisce a ottobre–novembre. 100 bulbi = circa 1 grammo di zafferano l'anno.",1],
    ["Cavoli (tutti)","trapianto","Entro il 20: dopo, cavolfiori e broccoli non fanno in tempo. Cavolo nero e verza ancora fino a fine mese.",0],
    ["Finocchio","trapianto","Entro il 10, poi rischi il gelo prima del grumolo.",0],
    ["Radicchio, scarola, indivia, pan di zucchero","trapianto","Tutto il mese.",0],
    ["Cime di rapa","semina","Le vere, da autunno (Quarantina, Sessantina): semina a spaglio da metà agosto, raccolta da fine ottobre. Insolite da noi ma perfette con il fresco.",1],
    ["Cavolo cinese (pe-tsai), pak choi, tatsoi, mizuna, komatsuna, senape","semina","Insoliti: gli \"orientali\" da autunno crescono velocissimi con il fresco, si mangiano crudi, saltati e in zuppa, e reggono le prime gelate. Semina da metà agosto.",1],
    ["Daikon, ravanello nero, ravanelli, rape","semina","Tutto il mese.",0],
    ["Spinacio, valerianella, lattughe da inverno, rucola","semina","Dal 20 in poi. Prima fa troppo caldo e lo spinacio non nasce.",0],
    ["Bietola, cicoria da taglio, prezzemolo, cerfoglio","semina","Tutto il mese, in ombra parziale.",0],
    ["Carote (ultima chiamata)","semina","Entro il 10, sotto TNT a ottobre: carote piccole e dolci a dicembre.",0],
    ["Cipolla bianca invernale","semenzaio","Fine mese in cassetta: piantine da trapiantare a ottobre–novembre.",0],
    ["Fragole","impianto","Fine agosto–settembre: il momento migliore dell'anno per piantarle.",0],
    ["Erba cipollina, aglio orsino, rabarbaro (divisione)","impianto","Fine mese: dividi i cespi vecchi. Insolito l'aglio orsino: bulbi a fine estate in un angolo ombroso e umido, e a marzo hai il pesto più buono dell'anno.",1],
    ["Sovescio autunnale (segale + veccia, o favino)","semina","Dal 20 su tutto quello che si libera.",0]
  ],
  raccolta:"Pomodori a pieno ritmo, peperoni, melanzane, zucchine, cetrioli, fagioli (freschi e da secco), mais, meloni e angurie, carote, barbabietole, patate da conservazione, cipolle, fagiolo dall'occhio, ceci, quinoa e amaranto (fine mese), physalis, tomatillo, cucamelon, prugne, pere e mele precoci, more, fichi (fine mese).",
  lavori:[
    "Conserve: passata di pomodoro, pomodori secchi nell'essiccatoio, peperoni sott'olio, giardiniera, marmellate",
    "Raccogli i fagioli da secco quando i baccelli sono cartacei, lasciali asciugare bene e metti nel congelatore 3 giorni contro il tonchio",
    "Intreccia cipolle e aglio, conserva le patate al buio a 8–12 °C",
    "Semina la sera e copri le semine con TNT bagnato o cartone finché non nascono",
    "Prepara le aiuole d'autunno: compost e acqua il giorno prima del trapianto",
    "Ombreggia i trapianti di cavoli per 5 giorni",
    "Controlla cavolaia (bruchi verdi) sui cavoli nuovi: rete anti-insetto fine subito dopo il trapianto risolve tutto",
    "Ordina l'aglio da piantare a ottobre e i bulbi di zafferano",
    "Salva i semi: pomodori, peperoni, fagioli, zucche, girasoli",
    "Raccogli i meloni quando il picciolo si stacca con un tocco"
  ] },

{ id:"settembre", nome:"Settembre", sotto:"L'orto cambia pelle: si tolgono le estive e si seminano le foglie da inverno. È l'ultimo mese per i trapianti all'aperto senza protezione.",
  clima:"Giornate ancora calde, notti a 8–10 °C dalla seconda metà. Prima possibile brinata negli ultimi giorni, di solito no.",
  piante:[
    ["Spinacio","semina","Semina diretta a righe. Raccogli a novembre e ancora a fine inverno. Regge il gelo.",0],
    ["Valerianella (songino)","semina","Fitta, a spaglio. Nasce lenta, poi la raccogli tutto l'inverno a foglia.",0],
    ["Rucola, ravanelli, lattuga da taglio, cicoria da taglio","semina","Semina diretta entro metà mese; poi sotto tunnel.",0],
    ["Cime di rapa, mizuna, tatsoi, pak choi, senape","semina","Ultima finestra, entro il 15.",1],
    ["Bietola da costa, prezzemolo, cerfoglio, coriandolo","semina","Cerfoglio e coriandolo con il fresco crescono meglio che in primavera.",0],
    ["Cavolo nero, verza, cappuccio","trapianto","Entro il 10, ultime piantine. Il cavolo nero è il più sicuro di tutti.",0],
    ["Radicchio, scarola, indivia, pan di zucchero, cavolo rapa","trapianto","Piantine entro il 15. Il radicchio rosso da inverno migliora con le prime gelate.",0],
    ["Finocchio","trapianto","Solo piantine di varietà precoce ed entro il 5: più tardi non fa in tempo.",0],
    ["Cipolla bianca invernale","semenzaio","In semenzaio o trapianto a ottobre; oppure bulbilli il mese prossimo.",0],
    ["Fragole","impianto","Piante nuove o stoloni radicati: settembre è il mese giusto per averle forti a maggio.",0],
    ["Zafferano","impianto","Ultima chiamata entro il 10: fiorisce comunque a fine ottobre.",1],
    ["Aglio orsino, rabarbaro, erba cipollina, asparagi (divisione)","impianto","Divisioni e bulbi delle perenni.",0],
    ["Sovescio (segale + veccia)","semina","Sulle aiuole che restano vuote: protegge l'argilla dalla pioggia e la ammorbidisce.",0],
    ["Bulbi di crocus, tulipani, narcisi lungo i bordi","impianto","Non da mangiare, ma i crocus e i narcisi a marzo sono il primo pasto delle api che poi impollinano l'orto.",0]
  ],
  raccolta:"Pomodori (ultimi), peperoni, melanzane, zucchine, fagioli, zucche (quando il picciolo secca), mais, patate, carote, bietole, lattughe, cavoli estivi, uva, mele, pere, fichi, noci a fine mese, nocciole, physalis, tomatillo, yacon a fine mese, quinoa, popcorn (lasciato seccare sulla pianta).",
  lavori:[
    "Raccogli gli ultimi pomodori, peperoni e zucchine; togli le piante finite e mettile nel compost (non quelle malate)",
    "Raccogli le zucche appena il picciolo secca; lasciale una settimana al sole a indurire la buccia",
    "Prepara le aiuole per l'inverno: vanga leggera e compost maturo, senza polverizzare l'argilla",
    "Semina il sovescio dove non pianti nulla fino a primavera",
    "Pianta le fragole nuove e togli gli stoloni in eccesso da quelle vecchie",
    "Continua a innaffiare le semine nuove: settembre qui può essere ancora secco",
    "Salva i semi di pomodoro, fagiolo e zucca delle piante migliori",
    "Controlla e ripara tunnel e TNT: a ottobre servono già",
    "Ordina l'aglio (varietà da freddo: Piacentino bianco, Rosso di Sulmona, Rosso di Nubia)",
    "Rincalza i finocchi trapiantati a luglio per imbianchire il grumolo"
  ] },

{ id:"ottobre", nome:"Ottobre", sotto:"Il mese dell'aglio, delle zucche e dello zafferano che fiorisce. Le prime gelate a fondovalle arrivano nella seconda metà: tieni il TNT a portata.",
  clima:"Prima brinata di solito tra il 15 e il 31, di notte a −1/−3 °C. Giornate ancora tiepide e umide, nebbie sul fiume.",
  piante:[
    ["Aglio","impianto","Dalla metà del mese. Bulbilli a 5 cm, punta in su, 15 cm tra uno e l'altro. In argilla: aiuola rialzata di 15–20 cm o aspetta febbraio.",0],
    ["Aglio elefante","impianto","Insolito: in realtà un porro che fa teste enormi dal sapore dolce. Si pianta come l'aglio, teste da 300 g a luglio.",1],
    ["Cipolla da bulbillo invernale, scalogno","impianto","Stesso discorso dell'aglio sul drenaggio.",0],
    ["Cipolla bianca (piantine)","trapianto","Quelle del semenzaio di fine agosto.",0],
    ["Fave","semina","Fine mese, sotto TNT, su aiuola rialzata. A 440 m con inverni a −8 è al limite: fai una fila di prova e il grosso a febbraio.",0],
    ["Piselli invernali (Meraviglia d'Italia, Rondo)","tunnel","Come le fave: solo protetti.",0],
    ["Spinacio, valerianella, lattughino, rucola, cerfoglio, coriandolo","tunnel","Ultime semine possibili, sotto tunnel o TNT: nasceranno con calma.",0],
    ["Alberi da frutto a radice nuda","impianto","Da fine mese: meli antichi (la Mela Rosa dei Sibillini è di qui), peri, susini, cotogno, ciliegio, noce, nocciolo. Buca larga, argilla mescolata a compost e mai fondo di plastica.",0],
    ["Azzeruolo, giuggiolo, nespolo germanico, sorbo domestico, corniolo","impianto","Insoliti: i frutti dimenticati che stavano in ogni orto marchigiano. Rustici, senza trattamenti, frutti da marmellata e liquori. Il giuggiolo vuole il posto più caldo.",1],
    ["Lamponi, more senza spine, ribes, uva spina, aronia, goji, sambuco","impianto","Da fine mese a marzo. Il sambuco per lo sciroppo di fiori a maggio.",0],
    ["Rabarbaro, luppolo, asparagi (divisione)","impianto","Divisione dei cespi vecchi.",0],
    ["Sovescio (segale)","semina","Ultima chiamata: la segale nasce anche a 5 °C, la veccia da sola non fa più in tempo.",0]
  ],
  raccolta:"Zucche (tutte, prima del gelo), cavoli, broccoli, cavolfiori, finocchi, radicchio, spinaci, cime di rapa, orientali, ravanelli, daikon, carote, bietole, porri, rape, sedano rapa, ultimi fagiolini e peperoni, physalis, yacon (prima del gelo), batata (prima del gelo), topinambur (dopo il gelo), noci, castagne, mele, pere, cachi, melagrane se ci sono, fiori di zafferano da fine mese (raccogli la mattina presto, stacca i tre stimmi, essicca).",
  lavori:[
    "Porta in casa zucche, yacon e batate prima della prima gelata: li rovina in una notte",
    "Raccogli i fiori di zafferano ogni mattina appena aperti; stimmi essiccati in 20 minuti a 40 °C nell'essiccatoio o vicino alla stufa",
    "Raccogli gli ultimi peperoni, anche verdi; le piante vanno via",
    "Monta tunnel e archetti sulle insalate e sugli spinaci",
    "Pacciama con foglie secche o paglia cavoli, finocchi, fragole, carciofi e rabarbaro",
    "Spargi letame maturo sulle aiuole vuote e lascialo in superficie: lo lavorerai a primavera",
    "Svuota e riponi tubi, filtro e programmatore dell'irrigazione prima del gelo",
    "Raccogli noci e castagne; le foglie del noce non vanno nel compost dei semenzai",
    "Lumache la sera dopo la pioggia: in autunno si moltiplicano nell'insalata",
    "Imbianca il cardo avvolgendolo in cartone per 3 settimane"
  ] },

{ id:"novembre", nome:"Novembre", sotto:"Si pianta poco e si protegge molto. Il cavolo nero dopo la prima brinata diventa più dolce: è il momento di mangiarlo.",
  clima:"Gelate regolari (−3/−6 °C), pioggia e nebbia. Il terreno è quasi sempre troppo bagnato per lavorarlo.",
  piante:[
    ["Aglio","impianto","Ultima chiamata, entro metà mese e solo se il terreno non è fradicio. Dopo, meglio febbraio.",0],
    ["Cipolla bianca (piantine)","trapianto","Le ultime, sotto TNT nelle notti fredde.",0],
    ["Fave e piselli","tunnel","Solo se hai il tunnel chiuso. All'aperto a fondovalle non ha senso.",0],
    ["Lattughino, valerianella, cerfoglio","tunnel","Semine di rimonta solo sotto tunnel: nasceranno con calma per febbraio.",0],
    ["Alberi da frutto a radice nuda","impianto","Tutto il mese, terreno permettendo: è il mese migliore per attecchire.",0],
    ["Lamponi, ribes, uva spina, more, mirtillo in vaso, kiwi (marzo meglio)","impianto","A radice nuda, in giornate senza gelo.",0],
    ["Vite","impianto","Barbatelle da novembre a marzo. Un pergolato di uva fragola o di un vitigno locale (Vernaccia nera, Maceratino) copre la tettoia in 3 anni.",0],
    ["Radicchio di Treviso tardivo (forzatura)","impianto","Insolito: scava le piante intere con la radice, mettile in secchi con acqua di fonte al buio in cantina: in 15–20 giorni hai i cespi rossi e croccanti.",1],
    ["Cicoria witloof (forzatura)","impianto","Insolito: come sopra, in sabbia al buio, per l'indivia belga fatta in casa.",1],
    ["Peperoncini e rocoto in vaso","impianto","Ritira in casa le piante in vaso: il rocoto e molti peperoncini sono perenni e l'anno dopo partono avvantaggiati.",1]
  ],
  raccolta:"Cavolo nero e verza dopo la brinata, cavolini di Bruxelles, cavolfiori, broccoli, finocchi (prima dei −4 °C), radicchio, cime di rapa, orientali, spinaci, valerianella, carote, pastinaca, scorzonera, navone, daikon, ravanello nero, topinambur, crosne, sedano rapa, porri, cardo imbiancato, ultimi cachi e mele tardive, zafferano (ultimi fiori).",
  lavori:[
    "Copri con TNT finocchi, bietole e radicchi nelle notti sotto zero",
    "Raccogli i finocchi prima dei −4 °C: sotto quella soglia marciscono",
    "Vanga grossolanamente le aiuole libere lasciando le zolle grosse: il gelo le sbriciola e l'argilla a primavera è più fine",
    "Rastrella le foglie e fanne una catasta a parte: tra un anno è terriccio per i semenzai",
    "Pulisci, affila e ungi vanga, zappa e cesoie prima di riporle",
    "Controlla che il tunnel sia ben ancorato: a novembre arriva il vento da nord",
    "Raccogli i cachi e mettili a maturare in casa con qualche mela",
    "Pacciama gli asparagi con 10 cm di letame o compost",
    "Proteggi il fico giovane e il melograno con TNT e paglia alla base",
    "Scava radicchio tardivo e witloof per la forzatura in cantina"
  ] },

{ id:"dicembre", nome:"Dicembre", sotto:"L'orto riposa e tu progetti. Si raccoglie quello che hai seminato a settembre e si prepara il 2027 sulla carta e in falegnameria.",
  clima:"Gelate a −5/−8 °C, prime nevi. Il terreno resta gelato per giorni: si lavora solo in casa e in cantina.",
  piante:[
    ["Aglio","impianto","Solo nelle giornate miti e a terreno asciutto. Altrimenti febbraio, non perdi niente.",0],
    ["Alberi e arbusti a radice nuda","impianto","Finché il terreno non gela. Meglio dicembre che marzo per attecchire.",0],
    ["Semenzaio di cipolla in casa","semenzaio","A fine mese in cassetta sul davanzale: piantine pronte per marzo.",0],
    ["Germogli e microgreens","semina","In cucina: crescione, ravanello, piselli, girasole in vaschetta.",0],
    ["Forzature in cantina","impianto","Witloof, radicchio tardivo, e a fine mese copri il rabarbaro con il secchio per anticipare.",1],
    ["Funghi su tronco (shiitake, pleurotus)","impianto","Insolito: tronchi di quercia o faggio tagliati a dicembre, inoculati con tasselli di micelio (si comprano online), tenuti all'ombra umida. Primi funghi dopo 9–12 mesi, poi per 4–5 anni.",1],
    ["Talee legnose di ribes, uva spina, fico, vite","impianto","Insolito e gratis: rametti da 25 cm interrati per due terzi in una cassetta di sabbia all'ombra. A primavera hanno le radici.",1]
  ],
  raccolta:"Cavolo nero, verza, cavolini, porri, radicchio, spinaci e valerianella dal tunnel, carote sotto pacciamatura, pastinaca, navone, scorzonera, topinambur, crosne, cardo, sedano rapa in cantina, mele e pere da conservazione, noci, cachi, radicchio e witloof forzati, funghi coltivati se hai i tronchi.",
  lavori:[
    "Raccogli e scopri il tunnel nelle ore di sole per far uscire l'umidità; scuoti la neve prima che lo schiacci",
    "Pota gli alberi da frutto nelle giornate asciutte sopra lo zero (non il ciliegio: si pota d'estate)",
    "Disegna l'orto 2027: ruota le famiglie, niente pomodori dove c'erano quest'anno",
    "Ordina i semi adesso: le varietà buone finiscono a gennaio. Prova almeno 3 insolite nuove all'anno",
    "Gira il compost una volta e coprilo",
    "Conserva i semi salvati in barattoli asciutti al buio, con l'etichetta",
    "Guarda dove ristagna l'acqua dopo le piogge: lì a primavera fai le aiuole rialzate",
    "Falegnameria: è il mese giusto per costruire aiuole, cassone freddo, cassette nido, essiccatoio",
    "Controlla patate, zucche, mele in cantina: togli quelle che marciscono",
    "Taglia le canne al fiume per i tutori dell'anno prossimo: d'inverno sono secche e leggere"
  ] }
];
