const RICETTE = [
/* GENNAIO */
{ mese:"gennaio", nome:"Zuppa di cavolo nero, fagioli e pane", tempo:"1 h · 4 persone", ing:["1 mazzo grande di cavolo nero (senza costa)","400 g fagioli lessati con il loro brodo","carota, cipolla, sedano","2 spicchi d'aglio, rosmarino","pane raffermo, olio buono"], passi:["Soffriggi carota, cipolla e sedano tritati con aglio e rosmarino.","Aggiungi metà dei fagioli frullati con il brodo e l'altra metà interi.","Unisci il cavolo nero a strisce, cuoci 30 minuti a fuoco basso. Sala.","Nel piatto: pane raffermo, zuppa sopra, olio crudo abbondante e pepe."], nota:"Il cavolo nero dopo la brinata è nettamente più dolce." },
{ mese:"gennaio", nome:"Purè di topinambur e patate", tempo:"35 min · 4 persone", ing:["500 g topinambur","300 g patate","50 g burro, 100 ml latte","sale, pepe, noce moscata"], passi:["Sbuccia i topinambur (o spazzolali bene) e le patate, tagliali a pezzi uguali.","Lessali in acqua salata 20 minuti, scola.","Schiaccia con burro e latte caldo. Noce moscata e pepe."], nota:"Il topinambur crudo a fettine sottili in insalata sa di carciofo. Vai piano le prime volte: fermenta nella pancia." },
{ mese:"gennaio", nome:"Porri gratinati al forno", tempo:"40 min · 4 persone", ing:["6 porri (solo il bianco e il verde tenero)","40 g burro, 2 cucchiai farina, 300 ml latte","60 g formaggio grattugiato (pecorino o groviera)","pangrattato, sale, pepe"], passi:["Taglia i porri a tronchetti di 8 cm e lessali 8 minuti. Scola bene.","Fai una besciamella veloce: burro, farina, latte, sale.","Disponi i porri in teglia, copri di besciamella, formaggio e pangrattato.","Forno 200 °C, 20 minuti."], nota:"Con lo speck a pezzetti dentro diventa un piatto unico." },
/* FEBBRAIO */
{ mese:"febbraio", nome:"Crema di sedano rapa e mela", tempo:"35 min · 4 persone", ing:["1 sedano rapa grosso","1 mela","1 cipolla, 1 patata","brodo, olio, sale, pepe, prezzemolo"], passi:["Soffriggi la cipolla, aggiungi sedano rapa, patata e mela a dadi.","Copri di brodo, cuoci 25 minuti.","Frulla, aggiusta di sale, servi con olio crudo e prezzemolo."], nota:"Il sedano rapa crudo grattugiato con maionese e senape è l'insalata francese \"rémoulade\"." },
{ mese:"febbraio", nome:"Pastinaca arrosto al miele", tempo:"40 min · 4 persone", ing:["800 g pastinache","2 cucchiai miele","olio, timo, sale, pepe"], passi:["Sbuccia le pastinache e tagliale a bastoncini.","Condisci con olio, sale, timo; forno 200 °C per 25 minuti.","Aggiungi il miele, altri 10 minuti finché caramellano."], nota:"Contorno perfetto per l'arrosto della domenica; anche le carote invernali così." },
{ mese:"febbraio", nome:"Frittata di germogli di luppolo (o di asparagi)", tempo:"20 min · 4 persone", ing:["1 mazzo germogli di luppolo (\"bruscandoli\")","6 uova, 50 g parmigiano","cipollotto, olio, sale, pepe"], passi:["Taglia i germogli a pezzetti, saltali 5 minuti con il cipollotto.","Sbatti le uova con formaggio, sale e pepe; unisci i germogli.","Cuoci a fuoco basso con coperchio 8 minuti, gira e finisci."], nota:"I germogli si raccolgono a fine febbraio–marzo quando sono lunghi 15–20 cm. Al posto loro: asparagi selvatici." },
/* MARZO */
{ mese:"marzo", nome:"Pesto di aglio orsino", tempo:"10 min · un barattolo", ing:["100 g foglie di aglio orsino","50 g noci o mandorle","50 g pecorino","100 ml olio, sale"], passi:["Lava e asciuga le foglie.","Frulla tutto insieme, aggiungendo olio a filo.","Copri di olio nel barattolo: in frigo dura 2 settimane."], nota:"Con la pasta, sulle bruschette, dentro le uova. L'aglio orsino si raccoglie a marzo-aprile prima della fioritura." },
{ mese:"marzo", nome:"Risotto ai porri e zafferano", tempo:"35 min · 4 persone", ing:["320 g riso","2 porri","una punta di stimmi di zafferano (in infusione in acqua calda)","brodo, burro, parmigiano, vino bianco"], passi:["Appassisci i porri a rondelle nel burro.","Tosta il riso, sfuma con il vino.","Brodo un mestolo alla volta per 16 minuti; a metà l'infuso di zafferano.","Manteca con burro e parmigiano."], nota:"Se hai lo zafferano tuo: 8–10 stimmi a persona bastano." },
{ mese:"marzo", nome:"Rabarbaro in composta per lo yogurt", tempo:"20 min · 4 vasetti", ing:["500 g coste di rabarbaro","150 g zucchero","succo di mezzo limone, 1 pezzetto di zenzero"], passi:["Taglia il rabarbaro a pezzi di 2 cm.","Cuoci con zucchero, limone e zenzero 10–15 minuti mescolando: si disfa da solo.","Invasa caldo."], nota:"Le foglie del rabarbaro sono tossiche: solo le coste. Con le fragole a maggio è la coppia classica." },
/* APRILE */
{ mese:"aprile", nome:"Agretti saltati con limone", tempo:"15 min · 4 persone", ing:["2 mazzi di agretti","1 spicchio d'aglio","olio, limone, sale, acciughe (facoltative)"], passi:["Togli la radice rosa e lava bene gli agretti.","Sbollentali 3 minuti, scola.","Saltali con aglio e olio, spegni, limone. Con le acciughe sciolte nell'olio è ancora meglio."], nota:"Croccanti, acidi, verdissimi. Con le uova o con la pasta." },
{ mese:"aprile", nome:"Vignarola (fave, piselli e carciofi)", tempo:"45 min · 4 persone", ing:["300 g fave sgranate","300 g piselli sgranati","4 carciofi (o 2 lattughe romane a spicchi)","1 cipollotto, guanciale (facoltativo), menta, olio, sale"], passi:["Rosola il cipollotto (e il guanciale) nell'olio.","Aggiungi carciofi a spicchi, poi fave e piselli, mezzo bicchiere d'acqua.","Coperchio, 20 minuti a fuoco basso. Menta fresca alla fine."], nota:"Ricetta laziale ma la valle del Chienti è a due passi. Con le prime fave piccole di maggio è perfetta." },
{ mese:"aprile", nome:"Frittata di erbe di primavera", tempo:"20 min · 4 persone", ing:["2 manciate di erbe miste: cerfoglio, erba cipollina, prezzemolo, foglie di rucola, cime di ortica sbollentate","6 uova, 40 g pecorino","olio, sale, pepe"], passi:["Trita le erbe grossolanamente.","Sbatti le uova con formaggio, sale, pepe; unisci le erbe.","Cuoci in padella a fuoco basso 8 minuti, gira e finisci."], nota:"L'ortica giovane sbollentata sa di spinacio con un fondo di nocciola." },
/* MAGGIO */
{ mese:"maggio", nome:"Fave e pecorino, con il pane", tempo:"5 min", ing:["Fave freschissime nel baccello","pecorino fresco o di media stagionatura","pane, sale"], passi:["Si sbucciano a tavola e si mangiano con il pecorino a pezzi.","Se le fave sono grandi, togli anche la pellicina."], nota:"Non è una ricetta: è il 1° maggio. Ma vale il pomeriggio di semina." },
{ mese:"maggio", nome:"Pasta con asparagi, piselli e guanciale", tempo:"25 min · 4 persone", ing:["320 g pasta corta","1 mazzo asparagi, 200 g piselli","80 g guanciale, 1 cipollotto","pecorino, pepe, olio"], passi:["Rosola il guanciale, togli e tieni da parte.","Nel grasso cuoci il cipollotto, gli asparagi a rondelle (punte a parte) e i piselli, 8 minuti con un mestolo d'acqua di cottura.","Aggiungi le punte, la pasta al dente, guanciale, pecorino e pepe; manteca con acqua di cottura."], nota:"" },
{ mese:"maggio", nome:"Fragole e rabarbaro al forno (crumble)", tempo:"45 min · 6 persone", ing:["400 g fragole, 300 g rabarbaro","100 g zucchero + 1 cucchiaio farina","Per il crumble: 150 g farina, 100 g burro freddo, 80 g zucchero, un pizzico di sale, fiocchi d'avena a piacere"], passi:["Mescola fragole e rabarbaro a pezzi con zucchero e farina, metti in una teglia.","Sbriciola burro, farina, zucchero e sale con le dita fino a briciole.","Copri la frutta, forno 180 °C per 35 minuti."], nota:"Con lo yogurt o la panna. Il rabarbaro bilancia la dolcezza delle fragole." },
/* GIUGNO */
{ mese:"giugno", nome:"Fiori di zucchina ripieni al forno", tempo:"30 min · 4 persone", ing:["12 fiori di zucchina","250 g ricotta, 1 uovo, 40 g parmigiano","menta o basilico, scorza di limone, sale, pepe, olio"], passi:["Togli il pistillo dai fiori con delicatezza.","Mescola ricotta, uovo, formaggio, erbe, scorza, sale e pepe.","Riempi i fiori con un cucchiaino, chiudi torcendo le punte.","Teglia unta, olio sopra, forno 200 °C per 15 minuti."], nota:"Raccogli i fiori maschi (quelli sul gambo lungo) la mattina presto quando sono aperti." },
{ mese:"giugno", nome:"Zucchine alla scapece con menta e aceto", tempo:"25 min + riposo · 4 persone", ing:["800 g zucchine","olio per friggere","2 spicchi d'aglio, menta fresca","aceto di vino bianco, sale"], passi:["Zucchine a rondelle, friggile dorate, scola su carta.","Nella pirofila alterna strati di zucchine, sale, menta e aglio a fettine.","Bagna con aceto, lascia riposare almeno 2 ore."], nota:"Meglio il giorno dopo. Si conserva 4 giorni in frigo: è la soluzione alle zucchine che non finiscono mai." },
{ mese:"giugno", nome:"Ciambellone con le ciliegie", tempo:"1 h · 8 persone", ing:["300 g farina, 200 g zucchero, 3 uova","100 ml olio di semi, 100 ml latte","1 bustina di lievito, scorza di limone","300 g ciliegie snocciolate"], passi:["Sbatti uova e zucchero, aggiungi olio, latte, scorza.","Unisci farina e lievito; poi le ciliegie infarinate.","Stampo a ciambella, forno 180 °C per 40 minuti."], nota:"Le ciliegie infarinate non vanno tutte sul fondo." },
/* LUGLIO */
{ mese:"luglio", nome:"Panzanella con i primi pomodori", tempo:"15 min + riposo · 4 persone", ing:["400 g pane raffermo","500 g pomodori maturi","1 cipolla rossa, 1 cetriolo","basilico, olio, aceto, sale"], passi:["Bagna il pane in acqua e aceto, strizza e sbriciola.","Aggiungi pomodori a pezzi, cipolla a fettine, cetriolo, basilico.","Olio, sale; riposo 30 minuti."], nota:"" },
{ mese:"luglio", nome:"Fagiolini in umido con pomodoro", tempo:"35 min · 4 persone", ing:["600 g fagiolini","400 g pomodori pelati o passata","1 cipolla, 1 spicchio d'aglio","olio, basilico, sale"], passi:["Soffriggi cipolla e aglio.","Aggiungi il pomodoro, 5 minuti, poi i fagiolini spuntati e mezzo bicchiere d'acqua.","Coperchio, 25 minuti. Basilico alla fine."], nota:"Con un uovo in camicia sopra è cena." },
{ mese:"luglio", nome:"Sciroppo di lamponi", tempo:"30 min · 1 litro", ing:["1 kg lamponi","600 g zucchero","succo di 1 limone"], passi:["Scalda i lamponi con mezzo bicchiere d'acqua 10 minuti, passali al setaccio.","Rimetti sul fuoco con zucchero e limone, 10 minuti.","In bottiglie sterilizzate: dura tutto l'inverno in cantina."], nota:"Un dito nel bicchiere con acqua frizzante. Con le more identico." },
/* AGOSTO */
{ mese:"agosto", nome:"Passata di pomodoro da conserva", tempo:"3 h · circa 6 bottiglie da 1 kg", ing:["10 kg pomodori maturi (San Marzano o da conserva)","basilico, sale"], passi:["Lava i pomodori, tagliali a metà, scolali un'ora in un cesto per perdere acqua.","Cuoci 20 minuti in una pentola grande, poi passa al passapomodoro.","Rimetti sul fuoco 10 minuti, sala poco.","Bottiglie con una foglia di basilico, riempi caldo, tappa, e sterilizza 30 minuti in acqua bollente coprendo con stracci."], nota:"Rispetta la sterilizzazione: il botulino non è una leggenda." },
{ mese:"agosto", nome:"Peperonata", tempo:"45 min · 4 persone", ing:["1 kg peperoni misti","400 g pomodori","2 cipolle, 1 spicchio d'aglio","olio, aceto, sale, basilico"], passi:["Cipolle a fettine nell'olio finché sono trasparenti.","Peperoni a strisce, 15 minuti mescolando.","Pomodori a pezzi, sale, coperchio, 20 minuti. Un cucchiaio d'aceto alla fine."], nota:"Il giorno dopo è meglio. Sott'olio in vasetti sterilizzati dura un mese." },
{ mese:"agosto", nome:"Salsa verde di tomatillo", tempo:"20 min · 1 ciotola", ing:["500 g tomatillo (senza il cartoccio)","1 cipolla piccola, 1 spicchio d'aglio","1 peperoncino verde, coriandolo fresco","succo di lime, sale"], passi:["Arrostisci i tomatillo in padella a secco o sotto il grill finché scuriscono.","Frulla con cipolla, aglio, peperoncino, coriandolo, lime e sale.","Servi con le patate arrosto, il pollo alla griglia, le uova."], nota:"È la ragione per coltivare il tomatillo." },
/* SETTEMBRE */
{ mese:"settembre", nome:"Frittata di spinaci e pecorino", tempo:"20 min · 4 persone", ing:["500 g spinaci","6 uova","60 g pecorino","1 spicchio d'aglio, olio, sale, pepe, noce moscata"], passi:["Cuoci gli spinaci con l'acqua che si portano dietro, strizza e trita.","Fai insaporire con aglio e olio 2 minuti.","Sbatti le uova con pecorino, sale, pepe, noce moscata; unisci gli spinaci.","Padella calda, coperchio, 6–7 minuti, gira e finisci."], nota:"Buona fredda il giorno dopo, nel panino." },
{ mese:"settembre", nome:"Minestra di bietole e ceci", tempo:"30 min · 4 persone", ing:["1 mazzo di bietole","300 g ceci lessati con il brodo","aglio, rosmarino, 2 pomodori","150 g pasta piccola o pane raffermo, olio, sale, pepe"], passi:["Coste a pezzetti nell'olio con aglio e rosmarino 5 minuti, poi le foglie a strisce.","Pomodori a pezzi e ceci con il brodo. 15 minuti.","Cuoci la pasta dentro o servi sul pane. Olio crudo e pepe."], nota:"Con i tuoi ceci di maggio, se ce l'hanno fatta." },
{ mese:"settembre", nome:"Marmellata di fichi e noci", tempo:"1 h · 4 vasetti", ing:["1 kg fichi","400 g zucchero","succo di 1 limone","80 g noci spezzate"], passi:["Fichi a pezzi con zucchero e limone, riposo 1 ora.","Cuoci 40 minuti mescolando, schiacciando i pezzi.","Aggiungi le noci, 5 minuti, invasa caldo e capovolgi."], nota:"Con il pecorino stagionato." },
/* OTTOBRE */
{ mese:"ottobre", nome:"Vellutata di zucca e rosmarino", tempo:"40 min · 4 persone", ing:["1 kg zucca pulita","1 cipolla, 1 patata","2 rametti di rosmarino","brodo, olio, sale, pepe, pane per i crostini"], passi:["Soffriggi la cipolla con il rosmarino intero.","Zucca e patata a pezzi, sale, brodo a filo. 25 minuti.","Togli il rosmarino, frulla.","Crostini tostati nell'olio, pepe, olio crudo."], nota:"La Delica viene più dolce e densa." },
{ mese:"ottobre", nome:"Finocchi gratinati", tempo:"45 min · 4 persone", ing:["4 finocchi","40 g burro, 3 cucchiai parmigiano","pangrattato, sale, pepe"], passi:["Finocchi a spicchi lessati 8 minuti, scola bene.","Teglia imburrata, sale, pepe, parmigiano, pangrattato, fiocchi di burro.","Forno 200 °C, 20 minuti."], nota:"Le barbe verdi tritate con olio e sale sono un pesto per la pasta." },
{ mese:"ottobre", nome:"Orecchiette con cime di rapa", tempo:"25 min · 4 persone", ing:["400 g orecchiette","800 g cime di rapa","4 filetti di acciuga, 2 spicchi d'aglio, peperoncino","olio, sale"], passi:["Pulisci le cime tenendo foglie tenere e infiorescenze.","Cuoci le cime nell'acqua della pasta; dopo 5 minuti butta la pasta nella stessa acqua.","Nella padella sciogli le acciughe nell'olio con aglio e peperoncino.","Scola pasta e cime, salta in padella un minuto."], nota:"Le tue cime di rapa seminate ad agosto, coltivate a 440 m: i pugliesi non ci credono." },
/* NOVEMBRE */
{ mese:"novembre", nome:"Risotto al radicchio", tempo:"35 min · 4 persone", ing:["320 g riso","1 cespo grande di radicchio rosso","1 scalogno, mezzo bicchiere di vino rosso","brodo, burro, parmigiano o pecorino"], passi:["Radicchio a strisce, tienine una manciata cruda.","Appassisci lo scalogno, aggiungi il radicchio 5 minuti.","Tosta il riso, sfuma con il vino rosso; brodo per 16–18 minuti.","Manteca; radicchio crudo sopra."], nota:"Se è troppo amaro, sbollenta il radicchio 1 minuto." },
{ mese:"novembre", nome:"Verza ripassata con salsiccia", tempo:"40 min · 4 persone", ing:["1 verza","3 salsicce","2 spicchi d'aglio, peperoncino, mezzo bicchiere di vino bianco","olio, sale"], passi:["Verza a strisce sbollentata 5 minuti.","Salsiccia sgranata rosolata con aglio e peperoncino, sfuma con il vino.","Aggiungi la verza, 20 minuti a fuoco medio."], nota:"Con la polenta o come sugo per la pasta corta." },
{ mese:"novembre", nome:"Cardo alla parmigiana (in umido)", tempo:"1 h 15 · 4 persone", ing:["1 kg coste di cardo imbiancato","1 limone","400 g passata, 1 cipolla","parmigiano, burro, farina, sale"], passi:["Pulisci i cardi togliendo i filamenti, tagliali a pezzi di 8 cm e mettili subito in acqua e limone.","Lessali 40 minuti in acqua salata con un cucchiaio di farina (restano chiari).","Passali in padella con burro e cipolla, aggiungi la passata, 20 minuti.","Parmigiano abbondante, forno 5 minuti a gratinare."], nota:"Il cardo è il carciofo dell'inverno: se lo hai imbiancato a ottobre, è tenero." },
/* DICEMBRE */
{ mese:"dicembre", nome:"Bruschetta con aglio, olio nuovo e cavolo nero", tempo:"15 min · 4 persone", ing:["8 fette di pane casereccio","foglie di cavolo nero","1 spicchio d'aglio dell'anno","olio nuovo, sale grosso"], passi:["Sbollenta il cavolo nero 3 minuti, strizza.","Tosta il pane, strofinalo con l'aglio caldo.","Cavolo sopra, sale grosso, olio nuovo a fiume."], nota:"La cosa più semplice e forse la più buona: dipende dall'olio." },
{ mese:"dicembre", nome:"Purè di navone e patate con burro nocciola", tempo:"35 min · 4 persone", ing:["500 g navone (rutabaga)","400 g patate","80 g burro, latte, sale, pepe"], passi:["Lessa navone e patate a pezzi 25 minuti.","Fai il burro nocciola: burro sul fuoco finché diventa color nocciola e profuma.","Schiaccia con latte caldo, sale, e versa il burro sopra."], nota:"Il navone da solo è troppo forte per molti; con le patate 1:1 è il purè d'inverno più buono." },
{ mese:"dicembre", nome:"Insalata di witloof, noci, mela e gorgonzola", tempo:"10 min · 4 persone", ing:["3 cespi di witloof (indivia belga) forzata","1 mela, una manciata di noci","100 g gorgonzola o pecorino di fossa","olio, aceto di mele, miele, sale"], passi:["Witloof a foglie, mela a fettine, noci spezzate.","Emulsiona olio, aceto, un cucchiaino di miele e sale.","Condisci, sbriciola il formaggio sopra."], nota:"Se hai forzato le radici in cantina a novembre, questa è la ricompensa." }
];
RICETTE.push(
/* GENNAIO +8 */
{ mese:"gennaio", nome:"Cavolini di Bruxelles arrosto con pancetta", tempo:"30 min · 4", ing:["600 g cavolini","100 g pancetta a dadini","olio, sale, pepe, aceto balsamico"], passi:["Taglia i cavolini a metà, condisci con olio e sale.","Forno 210 °C, 20 minuti, con la pancetta sparsa sopra a metà cottura.","Un giro di balsamico caldo."], nota:"Arrosto e non lessati: cambia tutto." },
{ mese:"gennaio", nome:"Minestra di verza, patate e cotenna", tempo:"1 h 15 · 4", ing:["1 verza","3 patate","150 g cotenna o guanciale","aglio, rosmarino, brodo, pane raffermo"], passi:["Cotenna a striscioline rosolata con aglio e rosmarino.","Verza a strisce e patate a dadi, brodo a filo, 50 minuti.","Sul pane raffermo con olio crudo."], nota:"" },
{ mese:"gennaio", nome:"Vellutata di pastinaca e patate", tempo:"35 min · 4", ing:["500 g pastinache","2 patate","1 cipolla, 1 mela","brodo, olio, noce moscata"], passi:["Soffriggi la cipolla, aggiungi tutto a pezzi.","Brodo a filo, 25 minuti.","Frulla; noce moscata, olio crudo, crostini."], nota:"Più dolce di quella di zucca." },
{ mese:"gennaio", nome:"Spinaci del tunnel saltati con uvetta e pinoli", tempo:"15 min · 4", ing:["600 g spinaci","30 g uvetta ammollata, 30 g pinoli","aglio, olio, sale"], passi:["Tosta i pinoli in padella a secco.","Aglio nell'olio, spinaci, 4 minuti con coperchio.","Uvetta e pinoli, sale."], nota:"Alla romana, ma con gli spinaci di gennaio che sono i più dolci." },
{ mese:"gennaio", nome:"Radicchio alla piastra con pecorino", tempo:"15 min · 4", ing:["2 cespi di radicchio (anche quello forzato)","olio, sale, aceto balsamico","pecorino a scaglie"], passi:["Radicchio a quarti, olio e sale.","Sulla piastra rovente 3 minuti per lato.","Balsamico e scaglie di pecorino."], nota:"" },
{ mese:"gennaio", nome:"Crostata di mele da conservazione e noci", tempo:"1 h · 8", ing:["Frolla: 300 g farina, 150 g burro, 100 g zucchero, 1 uovo, 1 tuorlo","4 mele, 60 g noci, 2 cucchiai zucchero, cannella"], passi:["Frolla veloce, riposo 30 minuti in frigo.","Stendi, mele a fettine a raggiera, noci, zucchero e cannella.","Forno 180 °C, 40 minuti."], nota:"Con le mele rugose di cantina viene meglio che con quelle nuove." },
{ mese:"gennaio", nome:"Insalata di cavolo cappuccio, carote e semi", tempo:"15 min · 4", ing:["mezzo cappuccio","2 carote","semi di girasole e di zucca","olio, aceto di mele, senape, sale"], passi:["Cappuccio a strisce sottilissime, sala e strizza con le mani 2 minuti: si ammorbidisce.","Carote grattugiate, semi tostati.","Emulsione olio-aceto-senape."], nota:"L'unica insalata cruda di gennaio che regge." },
{ mese:"gennaio", nome:"Zuppa di cipolle gratinata", tempo:"1 h · 4", ing:["800 g cipolle (delle tue conservate)","50 g burro, 1 cucchiaio farina","1 l brodo, mezzo bicchiere vino bianco","pane raffermo, groviera o pecorino"], passi:["Cipolle a fettine nel burro, 30 minuti a fuoco basso finché sono dorate.","Farina, vino, brodo; 20 minuti.","In cocotte con pane e formaggio, forno grill 10 minuti."], nota:"Cipolle di conservazione: sono più dolci di quelle nuove." },
/* FEBBRAIO +8 */
{ mese:"febbraio", nome:"Scorzonera in padella con burro e prezzemolo", tempo:"30 min · 4", ing:["600 g scorzonera","limone","40 g burro, prezzemolo, sale"], passi:["Sbuccia con i guanti (macchia), taglia a bastoncini, in acqua e limone.","Lessa 15 minuti, scola.","Salta nel burro con prezzemolo e sale."], nota:"Sa di asparago e nocciola." },
{ mese:"febbraio", nome:"Pasta e broccoli (con i cavolfiori d'inverno)", tempo:"30 min · 4", ing:["320 g pasta corta","1 broccolo o cavolfiore","aglio, peperoncino, acciughe","pecorino, olio"], passi:["Cime in acqua bollente 5 minuti, poi la pasta nella stessa acqua.","Aglio, peperoncino e acciughe nell'olio.","Scola e salta con pecorino e acqua di cottura."], nota:"" },
{ mese:"febbraio", nome:"Frittelle di cavolo nero (come pakora)", tempo:"25 min · 4", ing:["1 mazzo cavolo nero","150 g farina di ceci","cumino, sale, acqua","olio per friggere"], passi:["Cavolo a strisce sottili.","Pastella densa con farina di ceci, acqua, cumino, sale; unisci il cavolo.","Cucchiaiate in olio caldo, 3 minuti."], nota:"" },
{ mese:"febbraio", nome:"Porri in agrodolce", tempo:"25 min · 4", ing:["6 porri","3 cucchiai aceto di mele, 1 di miele","olio, sale, timo"], passi:["Porri a tronchetti rosolati nell'olio 10 minuti.","Aceto e miele, coperchio, 10 minuti.","Timo, freddi o tiepidi."], nota:"Si conservano 4 giorni in frigo." },
{ mese:"febbraio", nome:"Crema di topinambur con nocciole tostate", tempo:"35 min · 4", ing:["600 g topinambur","1 porro","brodo, olio, nocciole"], passi:["Porro nell'olio, topinambur a pezzi, brodo, 25 minuti.","Frulla.","Nocciole tostate e tritate sopra."], nota:"" },
{ mese:"febbraio", nome:"Cavolo rapa crudo in insalata con mela", tempo:"10 min · 4", ing:["2 cavoli rapa","1 mela","olio, limone, sale, erba cipollina"], passi:["Cavolo rapa sbucciato a bastoncini o grattugiato grosso.","Mela a fettine.","Olio, limone, sale, erba cipollina."], nota:"Croccante, sa di gambo di broccolo dolce." },
{ mese:"febbraio", nome:"Frittata di patate e cipolla (tortilla)", tempo:"40 min · 4", ing:["600 g patate","1 cipolla grande","6 uova","olio, sale"], passi:["Patate a fettine sottili e cipolla stufate nell'olio 20 minuti, coperte.","Scola e unisci alle uova sbattute salate.","Padella, 8 minuti per lato girando con un piatto."], nota:"Con le patate di cantina e le cipolle intrecciate: cena da dispensa." },
{ mese:"febbraio", nome:"Strudel di mele e uvetta", tempo:"1 h 15 · 8", ing:["1 rotolo di pasta sfoglia o pasta strudel","5 mele","80 g zucchero, 60 g uvetta, 40 g pinoli, pangrattato tostato nel burro, cannella"], passi:["Mele a fettine con zucchero, uvetta, pinoli e cannella.","Stendi la pasta, pangrattato, ripieno, arrotola.","Forno 180 °C, 40 minuti."], nota:"" },
/* MARZO +8 */
{ mese:"marzo", nome:"Risotto con i germogli di luppolo", tempo:"35 min · 4", ing:["320 g riso","1 mazzo germogli di luppolo","scalogno, brodo, burro, parmigiano, vino bianco"], passi:["Germogli a pezzetti, tienine le punte.","Risotto classico; germogli a metà cottura, punte a 2 minuti dalla fine.","Manteca."], nota:"Piatto veneto di marzo che funziona anche qui." },
{ mese:"marzo", nome:"Ravanelli e burro alla francese", tempo:"5 min", ing:["Un mazzo di ravanelli con le foglie","burro buono, sale grosso, pane"], passi:["Lava i ravanelli, lascia un pezzo di gambo.","Si mangiano intingendo nel burro e nel sale grosso, con il pane."], nota:"I primi ravanelli del tunnel. Le foglie tenere frullate con olio e mandorle sono un pesto." },
{ mese:"marzo", nome:"Zuppa di ortiche e patate", tempo:"35 min · 4", ing:["2 manciate di cime di ortica (con i guanti)","2 patate, 1 cipolla","brodo, olio, panna o ricotta"], passi:["Cipolla nell'olio, patate, brodo, 15 minuti.","Ortiche, 5 minuti.","Frulla; ricotta o panna sopra."], nota:"Le ortiche di marzo: solo le cime dei primi 15 cm." },
{ mese:"marzo", nome:"Frittata di cicoria e aglio orsino", tempo:"20 min · 4", ing:["cicoria di campo o catalogna","una manciata di foglie di aglio orsino","6 uova, pecorino, olio"], passi:["Cicoria sbollentata, strizzata e ripassata.","Aglio orsino tritato nelle uova con pecorino.","Frittata a fuoco basso."], nota:"" },
{ mese:"marzo", nome:"Vellutata di porri e patate", tempo:"35 min · 4", ing:["4 porri","3 patate","brodo, burro, erba cipollina"], passi:["Porri nel burro, patate, brodo, 25 minuti.","Frulla.","Erba cipollina fresca."], nota:"Il classico che non stanca." },
{ mese:"marzo", nome:"Insalata di spinaci novelli, uova sode e pancetta", tempo:"15 min · 4", ing:["200 g spinaci teneri crudi","3 uova sode","80 g pancetta croccante","olio, aceto, senape"], passi:["Pancetta croccante in padella.","Spinaci, uova a spicchi, pancetta.","Condimento con un cucchiaino di senape e il grasso della pancetta."], nota:"" },
{ mese:"marzo", nome:"Torta salata di bietole e ricotta", tempo:"1 h · 6", ing:["1 rotolo di pasta brisée","500 g bietole","250 g ricotta, 2 uova, 50 g parmigiano","noce moscata, sale"], passi:["Bietole lessate, strizzate, tritate.","Mescola con ricotta, uova, formaggio, noce moscata.","Nella brisée, forno 180 °C, 40 minuti."], nota:"Buona fredda per i lavori nell'orto." },
{ mese:"marzo", nome:"Gnocchi di ortica", tempo:"1 h · 4", ing:["800 g patate","150 g ortiche sbollentate e strizzate","250 g farina, 1 uovo, sale","burro e salvia"], passi:["Patate lesse schiacciate, ortiche tritate finissime, farina, uovo.","Cordoncini, tagli, incavo con la forchetta.","In acqua bollente finché salgono; burro fuso e salvia."], nota:"" },
/* APRILE +8 */
{ mese:"aprile", nome:"Risotto agli asparagi", tempo:"35 min · 4", ing:["320 g riso","1 mazzo asparagi","scalogno, brodo (fatto con i gambi degli asparagi), burro, parmigiano"], passi:["Gambi duri nel brodo, punte da parte.","Risotto con lo scalogno; asparagi a rondelle a metà, punte alla fine.","Manteca."], nota:"" },
{ mese:"aprile", nome:"Piselli alla fiorentina", tempo:"30 min · 4", ing:["500 g piselli freschi","60 g pancetta","aglio, prezzemolo, olio, brodo"], passi:["Pancetta e aglio nell'olio.","Piselli, mezzo bicchiere di brodo, 15 minuti coperti.","Prezzemolo."], nota:"" },
{ mese:"aprile", nome:"Insalata di rucola, pere e pecorino", tempo:"10 min · 4", ing:["rucola","1 pera","pecorino a scaglie, noci","olio, limone, miele"], passi:["Rucola lavata, pera a fettine.","Pecorino, noci.","Olio, limone, un cucchiaino di miele."], nota:"La rucola d'aprile è dolce; quella di luglio brucia." },
{ mese:"aprile", nome:"Crespelle agli spinaci e ricotta", tempo:"1 h · 4", ing:["8 crespelle (2 uova, 125 g farina, 250 ml latte)","400 g spinaci, 250 g ricotta, parmigiano","besciamella leggera"], passi:["Crespelle sottili.","Ripieno di spinaci strizzati, ricotta, parmigiano.","Arrotola, besciamella, forno 200 °C 15 minuti."], nota:"" },
{ mese:"aprile", nome:"Cipollotti alla brace con salsa verde", tempo:"20 min · 4", ing:["12 cipollotti","salsa verde: prezzemolo, capperi, acciuga, aglio, mollica, aceto, olio"], passi:["Cipollotti interi sulla brace o sulla piastra, 8 minuti.","Salsa verde tritata al coltello.","Cipollotti sbucciati dallo strato bruciato, salsa sopra."], nota:"Il calçot catalano, versione marchigiana." },
{ mese:"aprile", nome:"Pasta con le fave fresche, pecorino e menta", tempo:"20 min · 4", ing:["320 g pasta","300 g fave sgranate","cipollotto, olio, pecorino, menta"], passi:["Cipollotto nell'olio, fave, un mestolo d'acqua, 8 minuti.","Metà delle fave schiacciate con la forchetta.","Pasta, pecorino, menta."], nota:"" },
{ mese:"aprile", nome:"Torta di rabarbaro e mandorle", tempo:"1 h · 8", ing:["300 g rabarbaro","150 g burro, 150 g zucchero, 3 uova","100 g farina, 100 g mandorle tritate, lievito"], passi:["Burro e zucchero montati, uova, farina, mandorle, lievito.","Rabarbaro a pezzi sopra, premuti leggermente.","Forno 180 °C, 40 minuti."], nota:"" },
{ mese:"aprile", nome:"Uova in purgatorio con bietoline", tempo:"20 min · 4", ing:["400 g passata (la tua di agosto)","4 uova","bietoline giovani, aglio, peperoncino, pane"], passi:["Aglio e peperoncino nell'olio, passata, 10 minuti.","Bietoline a strisce, 3 minuti.","Uova rotte dentro, coperchio, 5 minuti. Pane."], nota:"" },
/* MAGGIO +8 */
{ mese:"maggio", nome:"Fragole con aceto balsamico e pepe", tempo:"5 min", ing:["Fragole","zucchero, aceto balsamico, pepe nero"], passi:["Fragole a metà con un cucchiaino di zucchero.","Poche gocce di balsamico, una macinata di pepe.","10 minuti di riposo."], nota:"Sembra strano, è buonissimo." },
{ mese:"maggio", nome:"Taccole saltate con aglio e limone", tempo:"10 min · 4", ing:["400 g taccole","aglio, olio, scorza di limone, sale"], passi:["Taccole spuntate.","Padella rovente con olio e aglio, 4 minuti.","Scorza di limone e sale."], nota:"" },
{ mese:"maggio", nome:"Risotto con piselli e lattuga", tempo:"35 min · 4", ing:["320 g riso","300 g piselli","1 lattuga romana","cipollotto, brodo, burro, parmigiano"], passi:["Cipollotto nel burro, riso, brodo.","Piselli a metà cottura, lattuga a strisce a 3 minuti dalla fine.","Manteca."], nota:"La lattuga cotta è dolce." },
{ mese:"maggio", nome:"Agretti con uova strapazzate", tempo:"15 min · 4", ing:["2 mazzi agretti","5 uova","olio, sale, pepe"], passi:["Agretti sbollentati 3 minuti.","Nell'olio, uova sbattute sopra, mescola a fuoco basso.","Pepe."], nota:"" },
{ mese:"maggio", nome:"Focaccia con cipollotti e rosmarino", tempo:"2 h 30 (con lievitazione) · 6", ing:["500 g farina, 350 ml acqua, 5 g lievito secco, 10 g sale","cipollotti, rosmarino, olio, sale grosso"], passi:["Impasto morbido, 2 ore di lievitazione.","In teglia unta, cipollotti a rondelle, rosmarino, olio, sale grosso.","Forno 230 °C, 20 minuti."], nota:"" },
{ mese:"maggio", nome:"Insalata di fave, pecorino e cicoria", tempo:"10 min · 4", ing:["fave piccole crude","pecorino a dadini","cicoria tenera o rucola","olio, sale, pepe"], passi:["Fave sgranate (piccole, senza pellicina).","Pecorino, cicoria.","Olio, sale, pepe."], nota:"" },
{ mese:"maggio", nome:"Sciroppo di fiori di sambuco", tempo:"30 min + 2 giorni · 1,5 l", ing:["20 ombrelle di fiori di sambuco","1 kg zucchero, 1 l acqua","2 limoni, 25 g acido citrico"], passi:["Sciroppo di acqua e zucchero, raffredda.","Fiori (scossi, non lavati) e limoni a fette nello sciroppo, 48 ore in frigo.","Filtra, acido citrico, in bottiglie."], nota:"Con acqua frizzante. Il sambuco fiorisce da noi a fine maggio." },
{ mese:"maggio", nome:"Pasta con asparagi selvatici e uova", tempo:"20 min · 4", ing:["320 g spaghetti","1 mazzo asparagi selvatici","3 uova, pecorino, pepe, olio, aglio"], passi:["Asparagi a pezzetti nell'olio con aglio, 5 minuti.","Spaghetti al dente in padella.","Fuori dal fuoco: uova sbattute con pecorino, mescola."], nota:"Come una carbonara senza guanciale." },
/* GIUGNO +8 */
{ mese:"giugno", nome:"Zucchine ripiene al forno", tempo:"50 min · 4", ing:["4 zucchine tonde o lunghe","200 g carne macinata (o ricotta e pane per la versione vegetariana)","uovo, parmigiano, prezzemolo, aglio, pangrattato"], passi:["Svuota le zucchine, trita la polpa e uniscila al ripieno.","Riempi, pangrattato e olio sopra.","Forno 190 °C, 35 minuti."], nota:"" },
{ mese:"giugno", nome:"Insalata di patate novelle, fagiolini e cipollotto", tempo:"25 min · 4", ing:["500 g patate novelle","300 g fagiolini","cipollotto, olive, olio, aceto, basilico"], passi:["Patate lesse con la buccia, fagiolini lessi.","A pezzi ancora tiepidi con cipollotto e olive.","Olio, aceto, basilico."], nota:"" },
{ mese:"giugno", nome:"Pesto di basilico", tempo:"10 min · 1 vasetto", ing:["50 g foglie di basilico","30 g pinoli, 1 spicchio d'aglio","60 g parmigiano, 20 g pecorino","100 ml olio, sale grosso"], passi:["Basilico asciutto, pinoli, aglio, sale nel mortaio o nel frullatore a impulsi.","Formaggi, olio a filo.","Copri di olio in vasetto."], nota:"Nel congelatore in vaschette da ghiaccio dura fino a Natale." },
{ mese:"giugno", nome:"Cetrioli in insalata con yogurt e menta", tempo:"10 min · 4", ing:["2 cetrioli","200 g yogurt greco","menta, aglio, olio, sale"], passi:["Cetrioli a fettine, sale, 10 minuti, strizza.","Yogurt, aglio grattato, menta.","Olio sopra."], nota:"" },
{ mese:"giugno", nome:"Carote novelle glassate", tempo:"20 min · 4", ing:["500 g carote piccole con un pezzo di gambo","30 g burro, 1 cucchiaino zucchero","acqua, sale, prezzemolo"], passi:["Carote in padella con burro, zucchero, sale e un dito d'acqua.","Coperchio, 10 minuti; poi scoperte finché l'acqua glassa.","Prezzemolo."], nota:"" },
{ mese:"giugno", nome:"Frittata di zucchine e fiori", tempo:"20 min · 4", ing:["3 zucchine","8 fiori di zucchina","6 uova, parmigiano, basilico"], passi:["Zucchine a rondelle saltate 8 minuti.","Uova con parmigiano e basilico, zucchine, fiori a pezzi.","Frittata a fuoco basso."], nota:"" },
{ mese:"giugno", nome:"Marmellata di fragole", tempo:"1 h · 4 vasetti", ing:["1 kg fragole","500 g zucchero","succo di 1 limone"], passi:["Fragole a pezzi con zucchero e limone, riposo 2 ore.","Cuoci 30–40 minuti schiumando, prova del piattino.","Invasa caldo e capovolgi."], nota:"Meno zucchero del solito: sa più di fragola, dura un anno in cantina." },
{ mese:"giugno", nome:"Vellutata fredda di piselli e menta", tempo:"25 min · 4", ing:["500 g piselli","1 cipollotto, 1 patata","brodo, menta, yogurt"], passi:["Cipollotto, patata, piselli, brodo: 15 minuti.","Frulla con la menta, raffredda in frigo.","Un cucchiaio di yogurt sopra."], nota:"Per le prime giornate calde." }
);
RICETTE.push(
/* LUGLIO +8 */
{ mese:"luglio", nome:"Pomodori ripieni di riso", tempo:"1 h 30 · 4", ing:["6 pomodori grossi tondi","150 g riso","basilico, aglio, olio, sale","4 patate a spicchi"], passi:["Svuota i pomodori, frulla la polpa con basilico e aglio, mescola con il riso crudo e olio.","Riempi a metà, coperchio; patate intorno.","Forno 180 °C, 1 ora e 15."], nota:"Il piatto romano dell'estate: si mangia tiepido." },
{ mese:"luglio", nome:"Ratatouille", tempo:"1 h · 6", ing:["2 melanzane, 3 zucchine, 2 peperoni","4 pomodori, 1 cipolla, 2 spicchi d'aglio","timo, basilico, olio, sale"], passi:["Ogni verdura cotta a parte nell'olio finché è dorata.","Unisci tutto con cipolla, aglio e pomodoro, 30 minuti a fuoco basso.","Basilico. Meglio il giorno dopo."], nota:"" },
{ mese:"luglio", nome:"Gazpacho", tempo:"15 min + frigo · 4", ing:["1 kg pomodori maturi","1 cetriolo, mezzo peperone, mezza cipolla, 1 spicchio d'aglio","100 g pane raffermo, olio, aceto, sale"], passi:["Frulla tutto con il pane ammollato.","Olio a filo, aceto, sale.","2 ore in frigo."], nota:"" },
{ mese:"luglio", nome:"Fagiolini in insalata con patate e pesto", tempo:"25 min · 4", ing:["400 g fagiolini","3 patate","2 cucchiai di pesto","olio"], passi:["Fagiolini e patate lessi.","Con il pesto allungato con acqua di cottura.","Tiepidi."], nota:"" },
{ mese:"luglio", nome:"Melanzane a funghetto", tempo:"30 min · 4", ing:["2 melanzane","aglio, olio, pomodorini","basilico, sale"], passi:["Melanzane a dadi fritte nell'olio finché sono dorate.","Aglio e pomodorini, 10 minuti.","Basilico."], nota:"" },
{ mese:"luglio", nome:"Pasta alla Norma", tempo:"40 min · 4", ing:["320 g pasta","1 melanzana","400 g pomodori pelati o passata","ricotta salata, basilico, aglio"], passi:["Melanzana a fette fritta.","Sugo veloce con aglio e pomodoro.","Pasta, melanzane, ricotta salata grattugiata, basilico."], nota:"" },
{ mese:"luglio", nome:"Crostata di albicocche", tempo:"1 h · 8", ing:["Frolla (300 g farina, 150 g burro, 100 g zucchero, 1 uovo, 1 tuorlo)","800 g albicocche","zucchero, mandorle a lamelle"], passi:["Frolla nella teglia.","Albicocche a metà con il taglio in su, zucchero, mandorle.","Forno 180 °C, 40 minuti."], nota:"" },
{ mese:"luglio", nome:"Cetrioli sottaceto (in barattolo)", tempo:"30 min + 3 settimane · 4 barattoli", ing:["1 kg cetriolini","1 l acqua, 500 ml aceto, 50 g sale, 30 g zucchero","aneto, aglio, pepe in grani, senape in grani"], passi:["Cetriolini lavati, in barattoli con aneto, aglio e spezie.","Salamoia bollente sopra, tappa.","Sterilizza 10 minuti; pronti dopo 3 settimane."], nota:"Con l'aneto del tuo orto." },
/* AGOSTO +8 */
{ mese:"agosto", nome:"Caponata", tempo:"1 h · 6", ing:["2 melanzane","sedano, cipolla, pomodoro","olive, capperi, aceto, zucchero, pinoli, basilico"], passi:["Melanzane a dadi fritte.","Sedano e cipolla nell'olio, pomodoro, olive, capperi, 15 minuti.","Melanzane, aceto e zucchero, 5 minuti. Fredda."], nota:"" },
{ mese:"agosto", nome:"Peperoni arrostiti sott'olio", tempo:"1 h · 3 vasetti", ing:["2 kg peperoni","aglio, basilico, sale","olio, aceto"], passi:["Peperoni arrostiti sulla brace o in forno a 220 °C finché la pelle è nera, chiusi in un sacchetto 15 minuti, spellati.","A strisce con sale, aglio e basilico, 1 minuto in acqua e aceto bollenti (1:1).","In vasetti coperti di olio, sterilizzati 20 minuti."], nota:"" },
{ mese:"agosto", nome:"Melanzane alla parmigiana", tempo:"1 h 30 · 6", ing:["3 melanzane","800 g passata","mozzarella, parmigiano, basilico","olio per friggere"], passi:["Melanzane a fette fritte (o grigliate per la versione leggera).","Strati: sugo, melanzane, mozzarella, parmigiano, basilico.","Forno 180 °C, 40 minuti."], nota:"" },
{ mese:"agosto", nome:"Insalata di pomodori, cipolla di Tropea e origano", tempo:"5 min · 4", ing:["pomodori maturi","cipolla rossa","origano secco (il tuo), olio, sale, aceto"], passi:["Pomodori a spicchi, cipolla a fettine sottili.","Origano sfregato tra le mani.","Olio, sale, un filo d'aceto. 15 minuti di riposo."], nota:"" },
{ mese:"agosto", nome:"Fiori di zucca fritti in pastella", tempo:"20 min · 4", ing:["12 fiori","150 g farina, 200 ml acqua frizzante fredda, sale","olio per friggere"], passi:["Pastella con acqua ghiacciata.","Fiori immersi e fritti 2 minuti.","Sale."], nota:"" },
{ mese:"agosto", nome:"Marmellata di prugne", tempo:"1 h · 4 vasetti", ing:["1 kg prugne snocciolate","500 g zucchero","limone, cannella"], passi:["Prugne a pezzi con zucchero e limone.","40 minuti mescolando, cannella.","Invasa caldo."], nota:"" },
{ mese:"agosto", nome:"Pannocchie alla brace con burro e sale", tempo:"20 min", ing:["Pannocchie di mais dolce","burro, sale, pepe, lime"], passi:["Pannocchie con le foglie sulla brace, 15 minuti girando.","Sfoglia, burro, sale.","Lime a piacere."], nota:"Il mais dolce va mangiato entro poche ore dalla raccolta: dopo diventa farinoso." },
{ mese:"agosto", nome:"Salsa di physalis e peperoncino", tempo:"20 min · 1 ciotola", ing:["300 g physalis","1 peperoncino, 1 cipolla piccola","lime, coriandolo, sale"], passi:["Physalis a metà, in padella con la cipolla 8 minuti.","Schiaccia, peperoncino, lime, sale.","Coriandolo fresco."], nota:"Agrodolce: con il pollo alla griglia e il formaggio fresco." },
/* SETTEMBRE +8 */
{ mese:"settembre", nome:"Zuppa di fagioli freschi e cotiche", tempo:"1 h 30 · 4", ing:["500 g borlotti freschi sgranati","150 g cotenne","pomodoro, cipolla, sedano, salvia, aglio","pane raffermo"], passi:["Cotenne sbollentate e a strisce.","Soffritto, borlotti, cotenne, pomodoro, acqua: 1 ora.","Sul pane con olio crudo."], nota:"" },
{ mese:"settembre", nome:"Peperoni ripieni di pane e acciughe", tempo:"50 min · 4", ing:["4 peperoni","150 g mollica, 4 acciughe, capperi, olive, prezzemolo, aglio","olio"], passi:["Ripieno di mollica bagnata, acciughe, capperi, olive, prezzemolo.","Peperoni a metà riempiti, olio.","Forno 190 °C, 35 minuti."], nota:"" },
{ mese:"settembre", nome:"Sugo di pomodoro e zucca per la pasta", tempo:"40 min · 4", ing:["300 g zucca","400 g passata","cipolla, salvia, olio, pecorino"], passi:["Cipolla e salvia nell'olio, zucca a dadini 10 minuti.","Passata, 20 minuti.","Sulla pasta con pecorino."], nota:"" },
{ mese:"settembre", nome:"Torta di mele con la Mela Rosa", tempo:"1 h · 8", ing:["4 mele (Mela Rosa dei Sibillini se le trovi)","3 uova, 150 g zucchero, 100 ml olio, 100 ml latte","250 g farina, lievito, scorza di limone"], passi:["Uova e zucchero, olio, latte, farina, lievito, scorza.","Metà delle mele a pezzi nell'impasto, metà a fettine sopra.","Forno 180 °C, 45 minuti."], nota:"" },
{ mese:"settembre", nome:"Uva e salsiccia in padella", tempo:"25 min · 4", ing:["4 salsicce","300 g uva (fragola o da tavola)","rosmarino, vino rosso"], passi:["Salsicce rosolate bucherellate.","Uva a chicchi e rosmarino, vino, coperchio 10 minuti.","Scoperte finché il sugo si restringe."], nota:"" },
{ mese:"settembre", nome:"Insalata di orientali (mizuna, tatsoi) con sesamo", tempo:"10 min · 4", ing:["mizuna e tatsoi teneri","salsa di soia, olio di sesamo, aceto di riso","semi di sesamo tostati"], passi:["Foglie lavate e asciutte.","Condimento: 1 cucchiaio soia, 1 cucchiaino olio di sesamo, 1 di aceto.","Sesamo."], nota:"" },
{ mese:"settembre", nome:"Crema di zucca e ceci con rosmarino", tempo:"40 min · 4", ing:["600 g zucca","300 g ceci lessati","rosmarino, aglio, olio, brodo"], passi:["Aglio e rosmarino nell'olio, zucca, brodo, 20 minuti.","Ceci, 5 minuti.","Frulla metà, lascia metà intera."], nota:"" },
{ mese:"settembre", nome:"Noci fresche, pecorino e miele", tempo:"5 min", ing:["Noci appena raccolte (da sbucciare della pellicina)","pecorino fresco","miele"], passi:["Noci fresche: si sbucciano e sono bianche e latte.","Con pecorino e un filo di miele."], nota:"Solo a settembre." },
/* OTTOBRE +8 */
{ mese:"ottobre", nome:"Risotto alla zucca", tempo:"35 min · 4", ing:["320 g riso","400 g zucca","cipolla, brodo, burro, parmigiano, salvia"], passi:["Cipolla nel burro, zucca a dadini 8 minuti.","Riso, brodo, 16 minuti: la zucca si disfa e lega.","Manteca; salvia fritta sopra."], nota:"" },
{ mese:"ottobre", nome:"Broccoli ripassati con aglio e peperoncino", tempo:"20 min · 4", ing:["1 broccolo","aglio, peperoncino, olio"], passi:["Cime sbollentate 4 minuti.","Ripassate nell'olio con aglio e peperoncino, schiacciandole un po'."], nota:"Contorno, o base per la pasta con acciughe." },
{ mese:"ottobre", nome:"Gnocchi di zucca con burro e salvia", tempo:"1 h · 4", ing:["800 g zucca arrostita","200 g patate lesse","250–300 g farina, 1 uovo, noce moscata, sale","burro, salvia, parmigiano"], passi:["Zucca arrostita e schiacciata bene (asciutta), patate, uovo, farina fino a impasto tenero.","Gnocchi, in acqua bollente.","Burro e salvia."], nota:"" },
{ mese:"ottobre", nome:"Cavolfiore gratinato", tempo:"45 min · 4", ing:["1 cavolfiore","besciamella (50 g burro, 50 g farina, 500 ml latte)","parmigiano, pangrattato, noce moscata"], passi:["Cime lessate 6 minuti.","In teglia con besciamella, parmigiano, pangrattato.","Forno 200 °C, 20 minuti."], nota:"" },
{ mese:"ottobre", nome:"Marmellata di cachi e zenzero", tempo:"1 h · 4 vasetti", ing:["1 kg polpa di cachi maturi","400 g zucchero","limone, zenzero fresco"], passi:["Polpa passata con zucchero, limone e zenzero grattato.","30 minuti mescolando.","Invasa caldo."], nota:"" },
{ mese:"ottobre", nome:"Chips di daikon e ravanello nero", tempo:"5 min", ing:["daikon o ravanello nero","sale, olio, aceto"], passi:["A fettine sottilissime con la mandolina.","Sale, olio, poche gocce di aceto.","Come stuzzichino o nel panino."], nota:"Il ravanello nero è piccante; il daikon dolce e acquoso." },
{ mese:"ottobre", nome:"Castagne al forno e vino nuovo", tempo:"40 min", ing:["Castagne","acqua, sale"], passi:["Incidi ogni castagna, 30 minuti in acqua.","Forno 220 °C, 25 minuti, o padella forata sul fuoco.","In un canovaccio 10 minuti."], nota:"" },
{ mese:"ottobre", nome:"Zuppa di porri, patate e cavolo nero", tempo:"45 min · 4", ing:["3 porri, 3 patate","mezzo mazzo cavolo nero","brodo, olio, pane"], passi:["Porri nell'olio, patate, brodo, 20 minuti.","Cavolo nero a strisce, 15 minuti.","Sul pane."], nota:"" },
/* NOVEMBRE +8 */
{ mese:"novembre", nome:"Cavolo nero e polenta", tempo:"1 h · 4", ing:["1 mazzo cavolo nero","300 g farina di mais (o polenta rapida)","aglio, olio, pecorino"], passi:["Polenta cotta.","Cavolo nero sbollentato e ripassato con aglio e olio.","Sulla polenta con pecorino e olio crudo."], nota:"" },
{ mese:"novembre", nome:"Pasta e ceci", tempo:"40 min · 4", ing:["300 g ceci lessati","200 g pasta mista","rosmarino, aglio, un cucchiaio di concentrato, olio, peperoncino"], passi:["Aglio e rosmarino nell'olio, concentrato, ceci e brodo.","Frulla un terzo dei ceci.","Pasta cotta dentro. Olio e peperoncino."], nota:"" },
{ mese:"novembre", nome:"Finocchi e arance in insalata", tempo:"10 min · 4", ing:["2 finocchi","2 arance","olive nere, olio, sale, pepe"], passi:["Finocchi a fettine sottili, arance a vivo.","Olive, olio, sale, pepe."], nota:"" },
{ mese:"novembre", nome:"Cavolini di Bruxelles con castagne", tempo:"30 min · 4", ing:["500 g cavolini","200 g castagne lessate","burro, pancetta, sale"], passi:["Cavolini lessati 8 minuti.","Nel burro con la pancetta, castagne, 10 minuti.","Sale e pepe."], nota:"Il contorno delle feste." },
{ mese:"novembre", nome:"Scorzonera fritta in pastella", tempo:"35 min · 4", ing:["500 g scorzonera","pastella di farina e acqua frizzante","olio, sale, limone"], passi:["Scorzonera sbucciata, lessata 10 minuti, a bastoncini.","In pastella e fritta.","Sale e limone."], nota:"" },
{ mese:"novembre", nome:"Crema di sedano rapa con olio al tartufo (o alle noci)", tempo:"35 min · 4", ing:["1 sedano rapa","1 patata, 1 porro","brodo, panna, olio al tartufo o olio di noci"], passi:["Porro, sedano rapa e patata a pezzi, brodo, 25 minuti.","Frulla con un goccio di panna.","Olio profumato sopra."], nota:"" },
{ mese:"novembre", nome:"Radicchio tardivo alla griglia con salsiccia", tempo:"20 min · 4", ing:["2 cespi radicchio tardivo","4 salsicce","olio, sale, balsamico"], passi:["Salsicce alla griglia.","Radicchio a quarti sulla griglia 3 minuti per lato.","Olio, sale, balsamico."], nota:"" },
{ mese:"novembre", nome:"Torta di zucca e cioccolato", tempo:"1 h · 8", ing:["300 g purea di zucca","3 uova, 150 g zucchero, 100 ml olio","200 g farina, lievito, 100 g cioccolato a pezzi, cannella"], passi:["Uova e zucchero, olio, purea, farina, lievito, cannella.","Cioccolato a pezzi.","Forno 180 °C, 45 minuti."], nota:"" },
/* DICEMBRE +8 */
{ mese:"dicembre", nome:"Pasta con cavolo nero e salsiccia", tempo:"30 min · 4", ing:["320 g orecchiette o pasta corta","1 mazzo cavolo nero","2 salsicce, aglio, peperoncino, pecorino"], passi:["Cavolo nero nell'acqua della pasta 5 minuti, poi la pasta.","Salsiccia sgranata rosolata con aglio e peperoncino.","Salta tutto con pecorino."], nota:"" },
{ mese:"dicembre", nome:"Porri e patate al forno con formaggio", tempo:"50 min · 4", ing:["4 porri, 4 patate","150 ml panna, 100 g formaggio (fontina o pecorino)","noce moscata, burro"], passi:["Patate a fettine sottili, porri a rondelle.","Strati in teglia imburrata, panna, formaggio, noce moscata.","Forno 190 °C, 40 minuti."], nota:"" },
{ mese:"dicembre", nome:"Vellutata di castagne e porri", tempo:"40 min · 4", ing:["300 g castagne lessate","2 porri","brodo, burro, panna, rosmarino"], passi:["Porri nel burro, castagne, brodo, rosmarino, 20 minuti.","Frulla con la panna.","Crostini."], nota:"" },
{ mese:"dicembre", nome:"Cavolo cappuccio stufato con mele e cumino", tempo:"45 min · 4", ing:["1 cappuccio (anche rosso)","2 mele, 1 cipolla","aceto di mele, zucchero, cumino, burro"], passi:["Cipolla nel burro, cappuccio a strisce, mele a pezzi.","Aceto, un cucchiaino di zucchero, cumino, coperchio, 35 minuti.","Con salsiccia o arrosto."], nota:"" },
{ mese:"dicembre", nome:"Pastinaca e carote arrosto con miele e timo", tempo:"40 min · 4", ing:["500 g pastinaca, 300 g carote","miele, timo, olio, sale"], passi:["A bastoncini con olio e sale.","Forno 200 °C, 25 minuti.","Miele e timo, 10 minuti."], nota:"" },
{ mese:"dicembre", nome:"Crostini con topinambur e pecorino di fossa", tempo:"20 min · 4", ing:["4 topinambur","pane, pecorino di fossa","olio, timo"], passi:["Topinambur a fettine sottili arrostite nell'olio.","Sul pane tostato con il pecorino.","Timo."], nota:"" },
{ mese:"dicembre", nome:"Spinaci alla panna gratinati", tempo:"30 min · 4", ing:["800 g spinaci","150 ml panna, 50 g parmigiano","noce moscata, burro"], passi:["Spinaci cotti e strizzati.","In teglia con panna, parmigiano, noce moscata.","Grill 10 minuti."], nota:"" },
{ mese:"dicembre", nome:"Biscotti alle noci e miele", tempo:"40 min · 30 biscotti", ing:["150 g noci tritate","200 g farina, 100 g burro, 80 g miele, 1 uovo","cannella, un pizzico di sale"], passi:["Burro e miele, uovo, farina, noci, cannella.","Palline schiacciate su teglia.","Forno 170 °C, 15 minuti."], nota:"Con le noci di settembre, per le feste." }
);
