/* Schede per ogni gruppo di piante.
   chiavi: nome, match (parole nel nome della coltura che portano qui), ricette (parole da cercare nei titoli),
   cons: {verde:[[pianta, perché]], giallo:[...], rosso:[...]}, conserva: HTML, storia: HTML (vuota = in scrittura) */
const SCHEDE = {
pomodoro:{ nome:"Pomodoro", match:["pomodor"], ricette:["pomodor","passata","gazpacho","panzanella","norma","ratatouille","purgatorio"],
 cons:{verde:[["Basilico","allontana la mosca bianca e l'afide, e i due si raccolgono insieme"],["Carota","occupa il terreno in basso, radici a profondità diversa"],["Aglio e cipolla","l'odore confonde gli afidi; la cipolla non compete"],["Tagete","le radici emettono sostanze che tengono lontani i nematodi"],["Prezzemolo e sedano","attirano i sirfidi, che mangiano gli afidi"],["Nasturzio","pianta-esca: gli afidi vanno su di lui"]],giallo:[["Peperone e melanzana","stessa famiglia: stanno bene insieme ma si passano le malattie, e l'anno dopo vanno tutti ruotati insieme"],["Lattuga e spinacio","vanno bene all'ombra del pomodoro solo in primavera; d'estate la competizione per l'acqua è troppa"]],rosso:[["Patata","stessa peronospora: una fila infetta l'altra in una settimana"],["Finocchio","le radici inibiscono la crescita di quasi tutto"],["Cavoli","competono per azoto e acqua, e il pomodoro li ombreggia"],["Mais","attira la nottua, che poi buca i pomodori"],["Cetriolo","si passano virus e oidio"]]},
 conserva:`<p><b>Passata e pelati</b>: bottiglie sterilizzate 30 minuti dopo l'invasatura; durano 2 anni. <b>Secchi</b>: a metà, sale, 2–3 giorni al sole o nell'essiccatoio, poi sott'olio o in sacchetti nel congelatore. <b>Congelati interi</b>: lavati e asciutti, in sacchetto; la buccia si toglie sotto l'acqua calda e vanno bene per i sughi. <b>Verdi a fine stagione</b>: in cassetta con qualche mela, maturano in 2–3 settimane; oppure in agrodolce sott'aceto. <b>Semi</b>: polpa fermentata 3 giorni in un bicchiere, lavata e asciugata: durano 5 anni.</p>`,
 storia:`<p>Il pomodoro nasce sulle Ande, tra Perù ed Ecuador, dove ancora oggi cresce spontanea una pianta con frutti grandi come un cece, il <i>Solanum pimpinellifolium</i>. Non furono gli Inca però a domesticarlo: la pianta risalì lentamente verso nord e furono i popoli del Messico a selezionare i frutti grossi. Il nome viene dal náhuatl <i>tomatl</i>, "cosa gonfia"; e il "pomodoro" italiano, "pomo d'oro", ci dice una cosa precisa: i primi che arrivarono in Italia erano gialli, non rossi.</p>
<p>Arrivò in Europa con le navi spagnole nei primi decenni del Cinquecento. La prima descrizione scritta è del 1544, nel <i>Commentarii</i> del medico senese Pietro Andrea Mattioli, che lo chiama "mala aurea" e ne parla come di una melanzana gialla che si mangia fritta nell'olio con sale e pepe. Ma per due secoli il pomodoro restò una curiosità da botanici e una pianta da vaso per i nobili: apparteneva alla stessa famiglia della belladonna e della mandragora, le foglie hanno un odore forte, e si sospettava fosse velenoso. Nel Nord Europa lo chiamavano "mela dell'amore" e lo si regalava come pianta ornamentale.</p>
<p>La svolta avvenne nel Sud Italia. Il primo ricettario con il pomodoro è napoletano, <i>Lo scalco alla moderna</i> di Antonio Latini, del 1692: una "salsa di pomodoro alla spagnola" con cipolla, timo e peperoncino. Nel Settecento a Napoli il pomodoro entrò nella cucina dei poveri e poi in quella di tutti; la pizza con il pomodoro è di fine Settecento, la pasta al pomodoro dei primi dell'Ottocento (la prima ricetta stampata è del 1839, nella <i>Cucina teorico-pratica</i> di Ippolito Cavalcanti). E fu un altro italiano, Francesco Cirio, a inventare nel 1856 a Torino l'industria della conserva, che trasformò un ortaggio di stagione in un ingrediente di tutto l'anno e portò il pomodoro italiano nel mondo.</p>
<p>Curiosità agronomica: il pomodoro è una pianta perenne che noi coltiviamo come annuale; in serra calda vive e produce per anni. Quelle "femminelle" che togli ogni settimana sono rami veri, e ogni pezzo di fusto interrato fa radici in pochi giorni: per questo si trapianta profondo. Il frutto, per la botanica, è una bacca; per la Corte Suprema degli Stati Uniti, dal 1893, è un ortaggio: un importatore aveva chiesto di non pagare il dazio sulle verdure sostenendo che il pomodoro fosse un frutto, e perse. Oggi esistono più di 10.000 varietà, e la maggior parte di quelle antiche, dal Cuore di bue al Costoluto, è stata selezionata da contadini italiani tra Ottocento e Novecento.</p>` },

patata:{ nome:"Patata", match:["patat"], ricette:["patat","tortilla","gnocchi"],
 cons:{verde:[["Fagiolo nano","fissa azoto e allontana la dorifora"],["Cavoli","radici a profondità diversa, non si disturbano"],["Mais","non compete per il terreno"],["Tagete e calendula","nematodi e dorifora"],["Rafano","tradizionalmente ai lati del campo contro la dorifora"]],giallo:[["Spinacio","va bene solo come coltura veloce prima che le patate coprano il terreno"],["Fava","bene, ma raccogli la fava prima di rincalzare"]],rosso:[["Pomodoro e melanzana","stessa famiglia, stessa peronospora e stessa dorifora"],["Zucca e cetriolo","le patate rendono i cetrioli più sensibili alla peronospora"],["Girasole","inibisce i tuberi"],["Finocchio","inibisce tutto"]]},
 conserva:`<p>Raccolte quando la pianta è secca, lasciate asciugare 2 ore all'ombra, mai lavate. In cantina o in un locale buio a 6–10 °C con aria, in cassette di legno o sacchi di juta: durano fino a marzo. Sopra i 12 °C germogliano, sotto i 4 diventano dolci. La luce le fa verdi e amare (solanina): quelle verdi non si mangiano. Controlla ogni 2 settimane e togli quelle molli. Le patate da seme si scelgono a novembre e si tengono a parte, in cassette alla luce da febbraio per far germogliare.</p>`,
 storia:`<p>La patata è la pianta più importante mai uscita dalle Americhe. Nasce sulle rive del lago Titicaca, tra Perù e Bolivia, a 3.800 metri, dove le popolazioni andine la coltivavano già 8.000 anni fa. Lì la patata non è una pianta sola: se ne conoscono ancora oggi più di 4.000 varietà, viola, nere, gialle, rosse, a forma di dita e di sasso, e nel museo del Centro Internazionale della Patata a Lima se ne conservano i tuberi vivi. Gli Inca avevano inventato il <i>chuño</i>: patate gelate di notte e calpestate di giorno per spremere l'acqua, che diventano un pane di patata secco capace di durare dieci anni. Era la scorta dell'impero.</p>
<p>Arrivò in Spagna intorno al 1570, nelle stive delle navi come cibo dell'equipaggio, e in Italia poco dopo, forse tramite i Carmelitani scalzi. Ma l'Europa non la volle. Non è nella Bibbia, si diceva; cresce sotto terra, come le cose del diavolo; è bitorzoluta come la lebbra. Per due secoli fu cibo per maiali e per affamati. Furono le carestie a cambiare le cose. In Prussia Federico II nel 1756 ordinò ai contadini di piantarla sotto minaccia di frustate. In Francia il farmacista Antoine Parmentier, prigioniero dei prussiani durante la Guerra dei Sette anni e sopravvissuto mangiando patate, fece piantare un campo di patate vicino a Parigi e lo fece sorvegliare da soldati solo di giorno: i contadini, convinti che una cosa così sorvegliata fosse preziosa, andavano a rubarle di notte. Funzionò. In Italia fu il naturalista Vincenzo Dandolo, in Lombardia, nei primi dell'Ottocento, a scrivere i manuali che la diffusero tra i contadini.</p>
<p>La patata cambiò la demografia dell'Europa: un ettaro di patate sfama quattro volte le persone di un ettaro di grano, e cresce dove il grano non cresce, in montagna, sull'argilla, sotto le piogge. Ma la dipendenza da una pianta sola fu anche la sua tragedia: in Irlanda nel 1845 la peronospora (<i>Phytophthora infestans</i>, "la divoratrice di piante") distrusse i raccolti per quattro anni di seguito; un milione di persone morirono e un altro milione emigrò. È lo stesso fungo che oggi ti annerisce le foglie dei pomodori dopo i temporali.</p>
<p>Curiosità: la patata è un fusto, non una radice: un tubero, cioè un ramo sotterraneo gonfio di amido; per questo ha gli "occhi", che sono gemme. È stata la prima verdura coltivata nello spazio, sullo Shuttle Columbia nel 1995. E il termine "patata" viene dalla confusione degli spagnoli tra la papa andina e la batata caraibica (la patata dolce): le due piante non sono nemmeno parenti.</p>` },

peperone:{ nome:"Peperone e peperoncino", match:["peperon","rocoto"], ricette:["peperon","peperonata","physalis e peperoncino"],
 cons:{verde:[["Basilico","stesso effetto che sul pomodoro"],["Carota e cipolla","radici a profondità diversa, cipolla contro gli afidi"],["Spinacio e lattuga","in primavera coprono il terreno tra le piante ancora piccole"],["Tagete","nematodi"]],giallo:[["Pomodoro e melanzana","stessa famiglia: bene insieme ma da ruotare insieme"],["Fagiolo","va bene ma il fagiolo rampicante lo ombreggia"]],rosso:[["Finocchio","inibisce"],["Cavoli","competizione e ombra"],["Patata","malattie in comune"]]},
 conserva:`<p><b>Arrostiti sott'olio</b> (spellati, sbollentati in acqua e aceto, sterilizzati 20 minuti). <b>Congelati</b> a strisce crudi, senza sbollentare. <b>Essiccati</b>: i peperoncini interi appesi a collane o nell'essiccatoio; i peperoni a strisce sottili nell'essiccatoio, poi macinati (paprika fatta in casa). <b>Sott'aceto</b> per i piccoli. Il peperoncino in polvere si conserva 1 anno in barattolo al buio. Le piante di peperoncino in vaso svernano in casa e ripartono a marzo.</p>`,
 storia:`<p>Peperone e peperoncino sono la stessa specie, <i>Capsicum annuum</i>, domesticata in Messico almeno 6.000 anni fa: nelle grotte di Tehuacán si sono trovati semi carbonizzati che risalgono a prima del mais. Gli Aztechi lo chiamavano <i>chilli</i> e lo usavano in tutto: nel cioccolato, nei tributi, come punizione per i bambini (il fumo dei peperoncini bruciati) e come arma. Il nome "peperone" invece è un errore di Colombo: cercava il pepe delle Indie e chiamò "pimienta" la prima pianta piccante che trovò nei Caraibi nel 1493. L'errore resta nel nome in mezza Europa.</p>
<p>Dall'Europa il peperoncino fece in cinquant'anni il giro del mondo: i portoghesi lo portarono in Africa, in India e in Cina, dove oggi è talmente radicato che sembra nativo. Non c'era piccante nel curry indiano né nella cucina del Sichuan prima del 1550. In Italia il peperoncino diventò il pepe dei poveri, la spezia che costava zero mentre il pepe vero valeva oro; il peperone dolce, invece, è una selezione moderna: le varietà grosse e senza piccante che coltiviamo oggi sono state fissate tra Ottocento e Novecento, e il gene che "spegne" la capsaicina è una mutazione singola.</p>
<p>La capsaicina, la molecola del piccante, non è un sapore ma un dolore: agisce sugli stessi recettori del calore e per questo "brucia". Gli uccelli non la sentono: mangiano i frutti e disperdono i semi interi, mentre i mammiferi, che li masticherebbero, vengono respinti. Una strategia perfetta della pianta, che l'uomo ha ribaltato coltivandola proprio per il bruciore. La scala Scoville, del 1912, misurava il piccante con quante diluizioni servissero perché un gruppo di assaggiatori non lo sentisse più: il peperone dolce sta a zero, il tuo rocoto tra 30.000 e 100.000, il Carolina Reaper oltre due milioni. Il rocoto, la specie andina a fiori viola e semi neri, è l'unico peperoncino che regge il freddo e vive anche dieci anni: in Perù crescono come alberi.</p>` },

melanzana:{ nome:"Melanzana", match:["melanzan"], ricette:["melanzan","norma","caponata","parmigiana","ratatouille"],
 cons:{verde:[["Fagiolo nano","azoto e dorifora"],["Basilico e timo","afidi"],["Tagete","nematodi"],["Spinacio","copertura del terreno in primavera"]],giallo:[["Pomodoro e peperone","stessa famiglia, ruotare insieme"]],rosso:[["Patata","dorifora e malattie"],["Finocchio","inibisce"],["Cavoli","competizione"]]},
 conserva:`<p><b>Sott'olio</b> a fette grigliate o sbollentate in acqua e aceto. <b>Congelate</b> solo dopo cottura (grigliate o fritte): crude diventano spugnose. <b>Essiccate</b> a fette sottili nell'essiccatoio, poi reidratate per i sughi (usanza siciliana). <b>Caponata e conserve in vasetto</b> sterilizzate. Fresche durano una settimana in frigo; a 10 °C in cantina qualcosa di più.</p>`, storia:`` },

zucchina:{ nome:"Zucchina", match:["zucchin"], ricette:["zucchin","fiori di zucca","ratatouille","scapece"],
 cons:{verde:[["Fagiolo rampicante e mais","le tre sorelle delle Americhe: il mais sostiene il fagiolo, la zucchina copre il terreno"],["Nasturzio","esca per gli afidi e attira gli impollinatori"],["Borragine e calendula","impollinatori"],["Ravanello","seminato tra le zucchine allontana la crisomela"]],giallo:[["Cetriolo, zucca, melone","stessa famiglia: oidio in comune e possibili incroci se salvi i semi"]],rosso:[["Patata","peronospora"],["Finocchio","inibisce"]]},
 conserva:`<p><b>Sott'olio</b> grigliate o alla scapece. <b>Congelate</b> a rondelle dopo 2 minuti di sbollentatura, o già cotte in padella. <b>Essiccate</b> a fette sottili (chips) nell'essiccatoio. Le zucchine lasciate crescere fino a 40 cm con buccia dura si conservano in cantina 2–3 mesi come le zucche. I fiori si mangiano il giorno stesso.</p>`, storia:`` },

zucca:{ nome:"Zucca", match:["zucca","zucche,","zucche "], ricette:["zucca"],
 cons:{verde:[["Mais e fagiolo rampicante","le tre sorelle"],["Nasturzio e borragine","impollinatori e afidi"],["Ravanello","crisomela"]],giallo:[["Zucchina, cetriolo, melone","stessa famiglia"]],rosso:[["Patata","malattie"],["Finocchio","inibisce"]]},
 conserva:`<p>Raccolte quando il picciolo è secco, con 5 cm di picciolo, lasciate una settimana al sole per indurire la buccia ("curing"). Poi in un locale asciutto a 10–15 °C, non a contatto tra loro, non in cantina umida: Butternut e Delica durano fino a marzo, Hokkaido fino a gennaio. Una volta tagliata: in frigo 5 giorni, o a dadi nel congelatore (cruda va bene), o in purea congelata in vasetti. I semi tostati con sale sono uno snack.</p>`,
 storia:`<p>Le zucche sono la più antica coltura delle Americhe: in Messico, nella grotta di Guilá Naquitz, sono stati trovati semi di zucca domesticata di 10.000 anni fa, tremila anni prima del mais. Le prime non si coltivavano per la polpa, amara e fibrosa, ma per i semi, ricchi di grasso, e per la buccia dura: svuotate, le zucche diventavano contenitori, galleggianti per le reti, maschere, strumenti. Le popolazioni native del Nord America inventarono la coltivazione delle "tre sorelle": mais che sostiene il fagiolo che fissa l'azoto, e sotto la zucca che copre il terreno con le sue foglie larghe e tiene lontani le erbacce e i procioni con i gambi spinosi.</p>
<p>In Europa prima del 1492 c'era una sola "zucca": la lagenaria, o zucca da fiasco, africana, che i Romani coltivavano per farne bottiglie e che la Bibbia cita come l'ombra di Giona. Le zucche americane arrivarono con le prime navi e furono subito capite, perché somigliavano a quella. A metà Cinquecento erano già nei giardini italiani, e i pittori le misero nei quadri: la zucca gialla a spicchi delle nature morte del Seicento è una <i>Cucurbita maxima</i>, la stessa specie della tua Marina di Chioggia e dell'Hokkaido.</p>
<p>Le zucche che coltivi appartengono a tre specie diverse che non si incrociano tra loro: <i>Cucurbita maxima</i> (Marina di Chioggia, Hokkaido, Delica, le giganti da record oltre i 1.200 chili), <i>Cucurbita moschata</i> (Butternut, la lunga di Napoli, la zucca violina) e <i>Cucurbita pepo</i>, che comprende zucchine, zucca spaghetti, patisson e le zucche ornamentali. Zucchine e zucca spaghetti sono cioè la stessa specie, e se le tieni vicine e salvi i semi, l'anno dopo hai dei mostri. L'Halloween con la zucca è un'invenzione americana dell'Ottocento: gli irlandesi intagliavano rape, e in America trovarono le zucche più facili da scavare. Nel Nord Italia, in Emilia e nel Mantovano, la tradizione dei tortelli di zucca è più vecchia: la ricetta è già nel <i>Libro nuovo</i> di Cristoforo Messisbugo, 1549.</p>` },

cetriolo:{ nome:"Cetriolo", match:["cetriol","carosello","barattiere","cucamelon"], ricette:["cetriol","gazpacho","sottaceto"],
 cons:{verde:[["Fagiolo","azoto"],["Aneto","tradizionalmente insieme, attira gli insetti utili"],["Lattuga","copre il terreno all'ombra"],["Girasole e mais","fanno da tutore"],["Ravanello","crisomela"]],giallo:[["Zucca e melone","stessa famiglia"]],rosso:[["Patata","peronospora"],["Aromatiche forti (salvia, rosmarino)","ne rallentano la crescita"],["Pomodoro","virus e oidio"]]},
 conserva:`<p>Fresco dura una settimana in frigo. Non si congela. <b>Sottaceto</b> in salamoia di acqua, aceto e sale (i cetriolini piccoli) o <b>in fermentazione</b> in acqua e sale al 3% per 2 settimane (i cetrioli "alla polacca", probiotici, in cantina fresca durano mesi). Con l'aneto del tuo orto.</p>`, storia:`` },

melone:{ nome:"Melone e anguria", match:["melon","anguri"], ricette:["melon","anguri"],
 cons:{verde:[["Mais","tutore e ombra parziale"],["Nasturzio","afidi"],["Ravanello","crisomela"]],giallo:[["Cetriolo e zucca","stessa famiglia"]],rosso:[["Patata","malattie"]]},
 conserva:`<p>Solo freschi, in cantina fresca una settimana. Il melone a pezzi si congela per i frullati; la buccia dell'anguria (parte bianca) si fa in agrodolce sottaceto, ricetta del Sud. Le angurie "da inverno" (varietà giapponesi) durano 3 mesi.</p>`, storia:`` },

fagiolo:{ nome:"Fagiolo", match:["fagiol","edamame","occhio"], ricette:["fagiol","borlott","fagiolini"],
 cons:{verde:[["Mais","tutore vivo per i rampicanti"],["Zucca e zucchina","tre sorelle"],["Carota","non compete"],["Cetriolo","bene insieme"],["Patata","dorifora"],["Cavoli","azoto"],["Santoreggia","tradizionalmente seminata a fianco: allontana gli afidi neri"]],giallo:[["Pomodoro","va bene con i fagioli nani, non con i rampicanti che ombreggiano"]],rosso:[["Aglio, cipolla, porro","rallentano tutti i legumi"],["Finocchio","inibisce"],["Girasole","competizione"]]},
 conserva:`<p><b>Fagiolini</b>: congelati dopo 3 minuti di sbollentatura; sott'olio; sottaceto. <b>Fagioli da sgranare freschi</b>: congelati crudi sgranati. <b>Fagioli secchi</b>: baccelli raccolti quando sono cartacei, sgranati, asciugati 2 settimane, poi 3 giorni nel congelatore contro il tonchio, e in barattoli di vetro al buio: durano 2 anni (dopo cuociono male). <b>Edamame</b>: congelato nei baccelli dopo sbollentatura.</p>`,
 storia:`<p>"Fagiolo" è una parola antica che per i Romani indicava un'altra pianta: il fagiolo dall'occhio, <i>Vigna unguiculata</i>, africano, arrivato in Italia attraverso l'Egitto e la Grecia. I Romani lo chiamavano <i>phaseolus</i>, ne mangiavano baccelli e semi e lo consideravano cibo pesante da contadini. Quello che oggi chiami fagiolo, il <i>Phaseolus vulgaris</i>, borlotto, cannellino, fagiolino, è invece americano, domesticato due volte in modo indipendente: in Messico circa 8.000 anni fa e sulle Ande, e le due linee si distinguono ancora oggi dal seme, piccolo il mesoamericano e grosso l'andino.</p>
<p>Arrivò in Italia in modo documentato: nel 1528 Papa Clemente VII ricevette dalla Spagna un sacchetto di fagioli e lo diede all'umanista Pierio Valeriano, canonico di Belluno, che li seminò e li diffuse in Veneto. Il fagiolo di Lamon, il borlotto per eccellenza, discende da quel sacchetto. Il nuovo fagiolo sostituì in fretta quello dall'occhio perché rendeva di più, cuoceva prima e poteva salire sui pali; nel Seicento era già la "carne dei poveri" di tutta Italia, e le Marche svilupparono decine di varietà locali, spesso legate a un solo paese: il fagiolo di Laverino, vicino a Fiuminata, il Solfino, il fagiolo di Monte Santa Maria in Gallo.</p>
<p>Il fagiolo, come tutti i legumi, non ha bisogno di azoto dal terreno: sulle radici ospita batteri (<i>Rhizobium</i>) in piccoli noduli rosa che catturano l'azoto dall'aria. Per questo l'agricoltura tradizionale lo alternava al grano e le "tre sorelle" americane funzionavano. Il seme crudo contiene una proteina tossica, la fasina, che si distrugge solo con la bollitura: cinque fagioli crudi bastano per stare male, ed è il motivo per cui in cottura lenta bisogna sempre far bollire forte almeno dieci minuti. La fagiolata e la festa dei fagioli con le cotiche sono nate come piatto della vigilia di Natale, perché di magro.</p>` },

fava:{ nome:"Fava", match:["fav"], ricette:["fav","vignarola"],
 cons:{verde:[["Patata precoce","la fava fissa azoto, la patata sfrutta lo spazio dopo"],["Cavoli","azoto"],["Lattuga e spinacio","tra le file, in primavera"],["Aneto e coriandolo","attirano coccinelle contro l'afide nero"],["Santoreggia","afidi"]],giallo:[["Pisello","stessa famiglia, stesse malattie; meglio a distanza"]],rosso:[["Aglio, cipolla, porro","rallentano i legumi"],["Finocchio","inibisce"]]},
 conserva:`<p>Fresche sgranate: congelate crude (o sbollentate 1 minuto se già grandi). Secche: baccelli lasciati seccare sulla pianta, sgranati e conservati in barattolo; 3 giorni in congelatore contro il tonchio. Le fave secche decorticate cuociono in mezz'ora e fanno il macco. Le punte cimate delle piante si mangiano saltate come spinaci.</p>`,
 storia:`<p>La fava è il legume più antico del Mediterraneo e l'unico grosso legume che l'Europa avesse prima delle Americhe. Coltivata nel Vicino Oriente da almeno 10.000 anni, era già nell'orto degli Egizi, dei Greci e dei Romani, che la chiamavano <i>faba</i>, da cui il nome della gens Fabia: le grandi famiglie romane si chiamavano dai legumi (Fabii, Lentuli, Cicerones, Pisones). In molte parti d'Italia si semina ancora per i Morti, il 2 novembre, e questa non è un'usanza casuale.</p>
<p>La fava infatti era la pianta dei morti. Pitagora la proibì ai suoi discepoli, e la leggenda dice che morì perché, inseguito dai nemici, si rifiutò di attraversare un campo di fave; i Romani la offrivano ai defunti nei Lemuria e la usavano nei banchetti funebri; il fiore, bianco con una macchia nera, veniva letto come un segno di lutto, e il gambo cavo come un canale con l'aldilà. Le "fave dei morti", i dolcetti di mandorle a forma di fava che si fanno a novembre nelle Marche e in Umbria, sono l'ultima traccia di quelle offerte. C'è però anche una spiegazione medica: nel Mediterraneo è diffuso il favismo, una carenza enzimatica ereditaria per cui mangiare fave fresche (o anche respirarne il polline) può distruggere i globuli rossi. Pitagora, forse, aveva visto qualcuno morire così.</p>
<p>Nell'orto la fava è la regina dell'inverno: sopporta il gelo fino a −5, fissa azoto, e le sue radici profonde spaccano l'argilla. Le punte si cimano in aprile quando arriva l'afide nero, che va sempre sulle cime: si tolgono e si mangiano. I baccelli piccoli si mangiano interi, le fave fresche con il pecorino sono il rito del 1° maggio, e quelle secche hanno sfamato l'Italia contadina fino al Novecento: il macco siciliano, la favata sarda, le fave e cicoria pugliesi sono la stessa idea, purea di fave e verdura amara, che risale ai Romani.</p>` },

pisello:{ nome:"Pisello e taccola", match:["pisell","taccol"], ricette:["pisell","vignarola"],
 cons:{verde:[["Carota e ravanello","tra le file"],["Lattuga e spinacio","tra le file, all'ombra della rete"],["Mais","tutore per i tardivi"],["Cetriolo e zucchina","dopo i piselli, sfruttano l'azoto"]],giallo:[["Fava","stessa famiglia"],["Fagiolo","stesse malattie"]],rosso:[["Aglio, cipolla, porro","rallentano"],["Finocchio","inibisce"]]},
 conserva:`<p>Sgranati e congelati crudi entro poche ore dalla raccolta: lo zucchero si trasforma in amido in un giorno. Taccole sbollentate 2 minuti e congelate. I piselli da secco (varietà a seme rugoso no, liscio sì) come i fagioli. In barattolo sterilizzati, come quelli in scatola.</p>`, storia:`` },

cece:{ nome:"Cece, cicerchia e lenticchia", match:["cec","cicerch","lenticch"], ricette:["cec","lenticch"],
 cons:{verde:[["Grano e orzo","la rotazione classica"],["Cavoli","dopo i legumi"],["Lattuga","tra le file"]],giallo:[["Altri legumi","stesse malattie"]],rosso:[["Aglio e cipolla","rallentano"]]},
 conserva:`<p>Solo secchi: piante estirpate intere quando i baccelli sono gialli, messe a seccare a testa in giù una settimana, battute su un telo, ventilate. Poi 3 giorni nel congelatore contro i tonchi e in barattolo al buio: 2–3 anni. Prima di cuocere: ammollo 12 ore (la cicerchia 24, cambiando l'acqua).</p>`, storia:`` },

cavoli:{ nome:"Cavoli (nero, verza, cappuccio, broccolo, cavolfiore, cavolini, cavolo rapa)", match:["cavol","verza","broccol","cappucc","cavolin"], ricette:["cavol","verza","broccol","cavolfior","cavolini","cappuccio"],
 cons:{verde:[["Fagiolo e fava","azoto"],["Sedano","si dice che allontani la cavolaia"],["Pomodoro (a distanza)","l'odore disturba la cavolaia"],["Aromatiche: timo, salvia, rosmarino, menta","confondono la farfalla bianca"],["Barbabietola e bietola","radici a profondità diversa"],["Nasturzio","esca per afidi e cavolaia"],["Cipolla","afidi"]],giallo:[["Lattuga","bene tra i cavoli piccoli, poi li ombreggiano"],["Patata","va, ma competono per il concime"]],rosso:[["Altri cavoli anno dopo anno","ernia del cavolo: mai nella stessa aiuola prima di 4 anni"],["Fragola","competizione e malattie"],["Rucola, ravanello, rapa","stessa famiglia"],["Aglio","rallenta"]]},
 conserva:`<p><b>Cavolo nero e verza</b>: in campo fino a marzo, sono la conserva di se stessi; a strisce sbollentate 2 minuti e congelate. <b>Cappuccio</b>: crauti (fermentato in sale al 2% per 3–6 settimane, dura mesi in cantina) o intero in cantina fino a febbraio. <b>Broccolo e cavolfiore</b>: cime sbollentate 3 minuti e congelate; sott'olio (giardiniera). <b>Cavolini</b>: congelati sbollentati. <b>Cavolo rapa</b>: in cantina nella sabbia fino a gennaio.</p>`,
 storia:`<p>Cavolo nero, verza, cappuccio, broccolo, cavolfiore, cavolini di Bruxelles e cavolo rapa sono una sola specie, <i>Brassica oleracea</i>, e discendono tutti da un cavolo selvatico che cresce ancora sulle scogliere dell'Atlantico e del Mediterraneo: una pianta dura, con foglie carnose e amare, buona più per le capre che per l'uomo. È il capolavoro della selezione contadina: in 2.500 anni, scegliendo una parte diversa della pianta, si è ottenuta la foglia (cavolo nero, verza), la gemma centrale (cappuccio), le gemme laterali (cavolini), il fiore (broccolo, cavolfiore), il fusto (cavolo rapa). Il cavolo nero toscano è tra i più antichi: assomiglia ancora al cavolo dei Greci, che non faceva "testa".</p>
<p>Greci e Romani lo consideravano la medicina universale. Catone il Censore, nel <i>De agri cultura</i>, dedica al cavolo il capitolo più lungo: cura tutto, dalle ferite alla malinconia, e mangiato crudo prima del banchetto permette di bere quanto si vuole. I Romani in effetti lo usavano contro la sbornia, e la scienza moderna dice che non avevano tutti i torti. Il cavolo cappuccio era così importante che i Romani lo portarono in tutte le province: i crauti tedeschi e la choucroute alsaziana nascono dalla fermentazione romana del cavolo nel sale. Il capitano Cook, nel Settecento, portò barili di crauti nei viaggi intorno al mondo e non perse un uomo per scorbuto.</p>
<p>Il broccolo e il cavolfiore sono italiani: il broccolo fu selezionato in Calabria e in Campania (nome da <i>brocco</i>, germoglio) e arrivò in Francia con Caterina de' Medici, nel resto d'Europa solo nel Settecento; il cavolfiore, "cavolo di Cipro", entrò in Italia nel Cinquecento e fu perfezionato in Toscana e nel Napoletano. Il romanesco, con le sue spirali frattali, è una selezione laziale del Cinquecento. I cavolini di Bruxelles sono i più giovani: fiamminghi, del Settecento. Curiosità agronomica: il cavolo nero è più dolce dopo la gelata perché la pianta trasforma l'amido in zuccheri per non gelare, un antigelo naturale. E i cavoli "sanno di cavolo" per i glucosinolati, composti dello zolfo che la pianta produce contro gli insetti e che oggi sono studiati per le loro proprietà antitumorali.</p>` },

cime:{ nome:"Cime di rapa e brassiche orientali (mizuna, pak choi, tatsoi, cavolo cinese, senape)", match:["cime di rapa","cime","mizuna","pak choi","tatsoi","komatsuna","senape","cinese","orientali"], ricette:["cime di rapa","orientali","mizuna"],
 cons:{verde:[["Lattuga e spinacio","stessi tempi, coprono insieme il terreno"],["Fagiolo","azoto"],["Aromatiche","cavolaia e altica"]],giallo:[["Cavoli","stessa famiglia: ok insieme, poi ruotare"]],rosso:[["Fragola","competizione"],["Stessa aiuola dei cavoli dell'anno prima","ernia"]]},
 conserva:`<p>Si mangiano fresche: in frigo 3–4 giorni. Cime di rapa sbollentate 2 minuti e congelate, oppure sott'olio dopo cottura. Pak choi e cavolo cinese fermentano benissimo: il kimchi coreano è fatto con il cavolo cinese e dura mesi in frigo. La senape a foglia si essicca e si macina per il seme.</p>`, storia:`` },

rapa:{ nome:"Rapa, navone, daikon, ravanello nero", match:["rapa,","rape","navone","rutabaga","daikon","nero d'inverno","ravanello nero"], ricette:["navone","daikon","ravanello nero","rapa"],
 cons:{verde:[["Pisello","azoto"],["Lattuga","tra le file"],["Menta e aromatiche","altica"]],giallo:[["Cavoli","stessa famiglia"]],rosso:[["Patata","competizione per il terreno"],["Altre brassiche dell'anno prima","ernia"]]},
 conserva:`<p>In cantina in cassette di sabbia umida: navone e ravanello nero fino a marzo, rapa e daikon 2 mesi. Il navone si può lasciare in campo sotto pacciamatura, regge −10. Daikon sottaceto (takuan) o a fette essiccate. Rape in agrodolce. Le foglie giovani della rapa sono le "cime".</p>`, storia:`` },

ravanello:{ nome:"Ravanello", match:["ravanell"], ricette:["ravanell"],
 cons:{verde:[["Carota","seminati insieme: il ravanello nasce prima e segna la fila, si raccoglie quando la carota ha bisogno di spazio"],["Lattuga","tra le file"],["Zucchina e cetriolo","allontana la crisomela"],["Pisello e fagiolo","azoto"],["Cerfoglio","ravanelli più piccanti e senza altica"]],giallo:[["Cavoli","stessa famiglia"]],rosso:[["Issopo","tradizionalmente incompatibile"]]},
 conserva:`<p>Freschi una settimana in frigo senza le foglie. Sottaceto a fette. Le foglie tenere si mangiano in frittata o in pesto. Non si congela. Lasciati salire a seme: i baccelli verdi sono croccanti e si mangiano crudi (ravanello "rat-tail").</p>`, storia:`` },

lattuga:{ nome:"Lattuga e insalate da taglio", match:["lattug","insalat","cicoria da taglio","lattughino"], ricette:["lattuga","insalata di"],
 cons:{verde:[["Carota, ravanello, cipolla","radici diverse, nessuna competizione"],["Fragola","stessa esposizione, la lattuga copre il terreno"],["Cetriolo e zucchina","lattuga all'ombra parziale d'estate"],["Cavoli","tra i cavoli giovani"],["Fagiolo e pisello","azoto"],["Aneto e cerfoglio","insetti utili"]],giallo:[["Pomodoro","solo in primavera, poi l'ombra e la sete sono troppe"]],rosso:[["Prezzemolo","tradizionalmente incompatibili"],["Sedano","competizione per l'acqua"]]},
 conserva:`<p>Non si conserva: si scaglionano le semine ogni 2 settimane per averla sempre. In frigo 4–5 giorni in un sacchetto con un foglio di carta. Le foglie esterne cotte vanno in vellutata o nel risotto (la lattuga cotta è dolce).</p>`, storia:`` },

radicchio:{ nome:"Radicchio, cicoria, catalogna, puntarelle, scarola, indivia, witloof", match:["radicch","cicori","catalogn","puntarell","scarol","indivi","witloof","pan di zucchero"], ricette:["radicch","cicoria","witloof","puntarelle","scarola","indivia"],
 cons:{verde:[["Carota e cipolla","radici diverse"],["Fagiolo","azoto"],["Finocchio","la cicoria è una delle poche che lo tollera"],["Lattuga","stessi tempi"]],giallo:[["Cavoli","competizione per lo spazio"]],rosso:[["Altre composite ripetute (lattuga, cardo, topinambur) nella stessa aiuola","stessa famiglia"]]},
 conserva:`<p>In campo sotto TNT fino a gennaio: il radicchio migliora con il gelo. Cespi con la radice in cantina nella sabbia, 1–2 mesi. Il radicchio tardivo e il witloof si forzano al buio per averli d'inverno. Scarola e indivia si imbianchiscono legandole 10 giorni prima della raccolta. Sott'olio dopo grigliatura. La radice di cicoria essiccata e tostata era il caffè di guerra.</p>`, storia:`` },

spinacio:{ nome:"Spinacio", match:["spinac","tetragon"], ricette:["spinac"],
 cons:{verde:[["Fragola","classica: copre il terreno tra le fragole"],["Fava e pisello","azoto, e lo spinacio sta all'ombra della rete"],["Cavoli","tra i cavoli giovani"],["Ravanello e lattuga","stessi tempi"],["Pomodoro e fagiolo","solo in primavera, prima che crescano"]],giallo:[["Bietola e barbabietola","stessa famiglia"]],rosso:[["Patata","competizione"],["Finocchio","inibisce"]]},
 conserva:`<p>Sbollentato 1 minuto, strizzato, in palline nel congelatore: è il metodo migliore. In frigo solo 2 giorni. Non si essicca bene. Il tetragonio (spinacio di Nuova Zelanda) si congela allo stesso modo.</p>`,
 storia:`<p>Lo spinacio è persiano. Il nome viene dal persiano <i>aspanakh</i>, e la Persia era il posto giusto: una pianta che vuole il fresco, cresce in fretta e si mangia giovane. Non lo conoscevano né i Greci né i Romani: nel Mediterraneo antico la verdura a foglia cotta era la bietola, la malva e il cavolo. Lo spinacio arrivò in Cina nel VII secolo, come dono del re del Nepal all'imperatore Tang, dove ancora lo chiamano "verdura persiana"; e in Europa con gli Arabi, attraverso la Sicilia e la Spagna, intorno all'anno Mille. Il grande agronomo andaluso Ibn al-Awwam, nel XII secolo, lo chiama "il principe delle verdure".</p>
<p>La sua fortuna europea è medievale e legata alla Quaresima: cresce d'inverno, cuoce in un minuto e si mangia nei giorni di magro. Nel Trecento è già negli orti dei monasteri e nei ricettari; nel Cinquecento Caterina de' Medici lo portò in Francia e da lì ogni piatto "alla fiorentina" nella cucina francese vuol dire "con gli spinaci". Le prime varietà avevano semi spinosi; quelle a seme liscio, più facili da seminare, sono del Cinquecento.</p>
<p>La leggenda del ferro è una delle bufale scientifiche più durature: nel 1870 un chimico tedesco pubblicò il contenuto di ferro degli spinaci con la virgola spostata (35 mg invece di 3,5 per 100 grammi), l'errore fu copiato per decenni e nel 1929 ispirò Braccio di Ferro. Lo spinacio ha meno ferro delle lenticchie, e per giunta l'acido ossalico che contiene ne blocca l'assorbimento. Il valore vero sta altrove: vitamina K, folati, luteina. Curiosità agronomica: lo spinacio "sale a seme" appena le giornate superano le 13 ore di luce, per questo in maggio fiorisce in fretta qualunque cosa tu faccia, e la semina buona è quella di settembre.</p>` },

valerianella:{ nome:"Valerianella (songino)", match:["valerianell","songino"], ricette:["valerianell"],
 cons:{verde:[["Fragola","classica copertura autunnale tra le fragole"],["Porro e cipolla","tra le file"],["Cavoli","sotto i cavoli invernali"]],giallo:[],rosso:[]},
 conserva:`<p>Si raccoglie a cespetti tutto l'inverno, non si conserva: in frigo 2 giorni. Lasciata fiorire si risemina da sola per sempre.</p>`, storia:`` },

rucola:{ nome:"Rucola", match:["rucol"], ricette:["rucol"],
 cons:{verde:[["Lattuga e spinacio","stessi tempi"],["Fagiolo","azoto"],["Cetriolo","copre il terreno"]],giallo:[["Cavoli","stessa famiglia"]],rosso:[["Fragola","competizione"]]},
 conserva:`<p>In frigo 3 giorni. Pesto di rucola sott'olio o congelato. La rucola selvatica è perenne: si taglia e ricresce per 3 anni.</p>`, storia:`` },

bietola:{ nome:"Bietola da costa e da orto", match:["bietol","bietolin"], ricette:["bietol"],
 cons:{verde:[["Cavoli","radici diverse"],["Fagiolo nano","azoto"],["Cipolla e aglio","tra le file"],["Lattuga","stessi tempi"]],giallo:[["Spinacio e barbabietola","stessa famiglia"]],rosso:[["Pomodoro","competizione"],["Mais","ombra"]]},
 conserva:`<p>Foglie e coste separate, sbollentate 2 minuti e congelate. Coste sott'olio dopo cottura. In campo produce da aprile a dicembre tagliando le foglie esterne: è la pianta che dà di più per lo spazio che occupa.</p>`, storia:`` },

carota:{ nome:"Carota", match:["carot"], ricette:["carot"],
 cons:{verde:[["Cipolla, porro, aglio","la classica coppia: l'odore della cipolla confonde la mosca della carota e viceversa"],["Ravanello","segna la fila"],["Pisello e fagiolo","azoto"],["Lattuga","tra le file"],["Pomodoro","la carota sotto il pomodoro"],["Rosmarino e salvia","mosca della carota"]],giallo:[["Sedano e finocchio","stessa famiglia: stessa mosca"]],rosso:[["Aneto","incrocia e disturba (stessa famiglia)"],["Prezzemolo","stessa mosca"]]},
 conserva:`<p>In campo sotto 15 cm di paglia o foglie fino a marzo: il sistema migliore. In cantina nella sabbia umida, senza foglie, fino a febbraio. Congelate a rondelle dopo sbollentatura. Sottaceto e in giardiniera. Essiccate a fette nell'essiccatoio per le minestre.</p>`,
 storia:`<p>La carota arancione non esiste in natura: è un'invenzione olandese di quattrocento anni fa. La carota selvatica, <i>Daucus carota</i>, cresce ovunque nei prati dell'Europa e dell'Asia (la riconosci: ombrella bianca con un fiorellino rosso al centro), e ha una radice bianca, sottile e legnosa. La domesticazione avvenne in Afghanistan e in Persia intorno al X secolo: le prime carote coltivate erano viola e gialle, e così arrivarono in Spagna con gli Arabi e in Italia nel Trecento. I Romani conoscevano solo la pastinaca e la carota selvatica, e nelle fonti antiche le due si confondono.</p>
<p>Le carote arancioni compaiono nelle nature morte fiamminghe del Seicento e sono il risultato della selezione fatta dagli orticoltori olandesi a partire da mutanti gialli. La storia che furono selezionate in onore della casa d'Orange è probabilmente una leggenda nata dopo, ma l'Olanda le diffuse in tutta Europa perché erano più dolci, più grosse e non tingevano la pentola come le viola. Le varietà moderne (Nantese, Chantenay, Flakkee) sono tutte dell'Ottocento francese.</p>
<p>Curiosità: la carota è una pianta biennale, e la radice grossa è la scorta che le serve per fiorire il secondo anno; per questo si raccoglie il primo. Il colore arancione è il betacarotene, che il corpo trasforma in vitamina A: la leggenda che le carote facciano vedere al buio fu diffusa apposta dall'aviazione britannica nel 1940 per non far capire ai tedeschi che i piloti inglesi avevano il radar. Nell'argilla la carota si biforca quando trova un sasso o una zolla dura: per questo qui le varietà corte e tonde vengono meglio.</p>` },

pastinaca:{ nome:"Pastinaca", match:["pastinac"], ricette:["pastinac"],
 cons:{verde:[["Cipolla e aglio","mosca della carota"],["Ravanello e lattuga","segnano la fila e coprono, la pastinaca nasce in 3 settimane"],["Pisello","azoto"]],giallo:[["Carota e sedano","stessa famiglia"]],rosso:[["Aneto","stessa famiglia"]]},
 conserva:`<p>La migliore conserva è il campo: si lascia in terra e si raccoglie da novembre a marzo, più dolce dopo ogni gelata. In cantina nella sabbia 3 mesi. Congelata dopo sbollentatura. Attenzione: le foglie con il sole possono irritare la pelle.</p>`, storia:`` },

barbabietola:{ nome:"Barbabietola", match:["barbabietol"], ricette:["barbabietol"],
 cons:{verde:[["Cipolla e aglio","tra le file"],["Cavoli","radici diverse"],["Lattuga","stessi tempi"],["Fagiolo nano","azoto"]],giallo:[["Bietola e spinacio","stessa famiglia"]],rosso:[["Fagiolo rampicante","ombra e si dice la inibisca"],["Senape","competizione"]]},
 conserva:`<p>In cantina nella sabbia fino a marzo, senza le foglie. Lessate e sottaceto in vasetto: il metodo classico. Congelate cotte a fette. Le foglie giovani come bietole.</p>`, storia:`` },

scorzonera:{ nome:"Scorzonera e scorzobianca", match:["scorzoner","scorzobianc"], ricette:["scorzoner"],
 cons:{verde:[["Cipolla","tra le file"],["Lattuga","copre"]],giallo:[["Radicchio e lattuga ripetuti","stessa famiglia"]],rosso:[]},
 conserva:`<p>In campo tutto l'inverno, o in cantina nella sabbia 3 mesi. Sbucciare con i guanti e mettere in acqua e limone. Congelata dopo sbollentatura.</p>`, storia:`` },

sedano:{ nome:"Sedano, sedano rapa, levistico", match:["sedano","levistic"], ricette:["sedano"],
 cons:{verde:[["Cavoli","il sedano allontana la cavolaia"],["Pomodoro","insetti utili"],["Porro e cipolla","tra le file"],["Fagiolo","azoto"],["Cetriolo","copre"]],giallo:[["Carota e finocchio","stessa famiglia"]],rosso:[["Mais","competizione per l'acqua"],["Patata","competizione"]]},
 conserva:`<p>Sedano rapa in cantina nella sabbia fino a marzo. Sedano a coste in cantina con le radici 1–2 mesi, o congelato a pezzi per i soffritti (con carota e cipolla, già tritato: il "soffritto pronto" nel congelatore). Foglie essiccate come dado. Il levistico essiccato è il "dado" delle nonne dell'Est.</p>`, storia:`` },

finocchio:{ nome:"Finocchio", match:["finocch"], ricette:["finocch"],
 cons:{verde:[["Cicoria e radicchio","tra i pochi che lo tollerano"],["Lattuga","in primavera"]],giallo:[["Cavoli","a distanza"]],rosso:[["Pomodoro, fagiolo, cetriolo, peperone, patata","il finocchio emette sostanze che inibiscono quasi tutto: va in un'aiuola a parte"],["Aneto e coriandolo","incrociano e si rovinano"]]},
 conserva:`<p>In cantina nella sabbia 1–2 mesi, o in campo sotto TNT fino ai −4. Sott'olio dopo grigliatura. Congelato a spicchi sbollentati. I semi del finocchio selvatico si raccolgono a settembre ed essiccano per la salsiccia e il pane.</p>`, storia:`` },

aglio:{ nome:"Aglio (anche elefante e orsino)", match:["aglio"], ricette:["aglio"],
 cons:{verde:[["Fragola","classica: l'aglio tra le fragole allontana funghi e insetti"],["Pomodoro","afidi"],["Carota","mosca"],["Lattuga","tra le file"],["Rosa e alberi da frutto","ai piedi contro afidi e bolla"],["Barbabietola","bene insieme"]],giallo:[["Cavoli","va bene ma li rallenta un po'"]],rosso:[["Fagiolo, pisello, fava","i legumi vicino all'aglio crescono la metà"]]},
 conserva:`<p>Raccolto quando metà delle foglie è gialla, lasciato una settimana al sole poi 2 all'ombra ventilata con le foglie: poi si intreccia (aglio bianco) o si taglia il gambo. In luogo asciutto, buio, ventilato, a 10–18 °C: il bianco dura fino a maggio, il rosso fino a febbraio. Mai in frigo (germoglia) né in sacchetti chiusi. Spicchi sott'olio solo dopo acidificazione in aceto e in frigo (botulino). Aglio nero: 3 settimane a 60 °C nel cuociriso. L'aglio orsino si fa in pesto.</p>`,
 storia:`<p>L'aglio viene dall'Asia centrale, dalle montagne tra Kirghizistan e Uzbekistan, dove cresce ancora selvatico, e da lì seguì le vie delle carovane in tutte le direzioni. È una delle piante più antiche coltivate dall'uomo: era nelle piramidi. Nella tomba di Tutankhamon c'erano bulbi d'aglio, e una tavoletta egizia racconta che gli operai delle piramidi ricevevano razioni di aglio e cipolla per la forza; uno sciopero degli operai, il primo della storia, sarebbe scoppiato per il ritardo delle razioni. Gli Ebrei nel deserto rimpiangevano "l'aglio e le cipolle d'Egitto".</p>
<p>Greci e Romani ne facevano cibo di soldati, marinai e contadini: Aristofane lo dà ai combattenti prima della battaglia, i legionari ne mangiavano uno spicchio al giorno, e Plinio elenca 61 malattie che cura. Ma l'aglio segnava anche la classe sociale: chi puzzava d'aglio era un plebeo, e nei templi non si entrava dopo averlo mangiato. Nel Medioevo era il rimedio contro la peste (l'"aceto dei quattro ladri" con aglio, con cui i saccheggiatori di Marsiglia si proteggevano dalle case dei morti) e contro il malocchio; la treccia d'aglio sulla porta è più antica di Dracula di secoli, e Bram Stoker nel 1897 prese l'idea dal folklore balcanico dove l'aglio teneva lontani i morti che tornano.</p>
<p>Oggi l'Italia ha i suoi agli: il Rosso di Nubia siciliano, il Bianco Piacentino, il Rosso di Sulmona che è a due passi da qui, l'aglione della Valdichiana grosso come un pugno e senza il bruciore. Curiosità agronomica: l'aglio coltivato non fa più semi da millenni, si riproduce solo per spicchi, e per questo ogni varietà è un clone antico di secoli. Il sapore viene dall'allicina, che non esiste nella pianta intera: si forma solo quando lo tagli, dall'incontro di due sostanze tenute in cellule separate, una difesa chimica contro chi morde. Se lo schiacci e aspetti dieci minuti prima di cuocerlo, ne produce di più. E l'aglio orsino dei boschi, che raccogli a marzo, è un'altra specie, <i>Allium ursinum</i>: si chiama così perché gli orsi lo mangiano appena escono dal letargo.</p>` },

cipolla:{ nome:"Cipolla, scalogno, cipollotto", match:["cipoll","scalogn"], ricette:["cipoll","scalogn","tortilla"],
 cons:{verde:[["Carota","la coppia classica"],["Lattuga e spinacio","tra le file"],["Barbabietola e bietola","bene"],["Fragola","funghi"],["Pomodoro","afidi"],["Camomilla","tradizionalmente un ciuffo ogni tanto"]],giallo:[["Cavoli","ok"]],rosso:[["Fagiolo, pisello, fava","rallenta i legumi"],["Salvia","incompatibili"]]},
 conserva:`<p>Raccolte quando il gambo si piega, lasciate 4–5 giorni al sole, poi 2 settimane all'ombra. Intrecciate o in rete, in luogo asciutto e ventilato a 5–15 °C: le dorate e le ramate durano fino a marzo, le bianche 2 mesi, le rosse 4. Non in frigo. Cipollotti e cipolle germogliate: tritate e congelate. Sott'aceto le piccole (borettane in agrodolce). Lo scalogno dura di più della cipolla.</p>`,
 storia:`<p>La cipolla viene dall'Asia centrale come l'aglio, e come l'aglio non esiste più selvatica nella forma coltivata: la coltiviamo da almeno 5.000 anni. Per gli Egizi era sacra: le sfere concentriche rappresentavano l'eternità, e si è trovata una cipolla nell'orbita di Ramses IV, mummificato con cipolle sul petto. Era anche la paga: gli operai delle piramidi ricevevano pane, birra, cipolle. I Greci la mangiavano cruda prima delle gare olimpiche; i Romani la portarono ovunque, e Apicio, nel primo ricettario dell'antichità, la mette in metà delle ricette. Plinio elenca le varietà coltivate a Pompei, e negli scavi si sono trovati gli orti con le cipolle ancora al loro posto.</p>
<p>Nel Medioevo era il cibo dell'inverno, quando non c'era altro; si pagavano gli affitti in cipolle e i medici la prescrivevano contro la calvizie e i morsi di cane. Colombo la portò ad Haiti nel 1493 ed è una delle prime piante europee coltivate in America. In Italia la cipolla è un catalogo di paesi: la rossa di Tropea, la dorata di Parma, la ramata di Milano, la rossa di Acquaviva, la bianca di Chioggia, la borettana di Boretto. Lo scalogno, che i Romani chiamavano "cipolla di Ascalona" dal porto palestinese, tornò in Europa con i crociati ed è la cipolla di Romagna.</p>
<p>Curiosità agronomica: la cipolla decide quando fare il bulbo in base alle ore di luce, non alla temperatura. Le varietà "da giorno lungo" fanno il bulbo solo con 14–16 ore di luce, quelle "da giorno corto" con 11–12: per questo una cipolla siciliana seminata qui a primavera non fa la testa, e una del Nord seminata in autunno non ne fa. Il pianto viene da una molecola volatile di zolfo che la cipolla libera quando la tagli, un gas irritante che nella pianta intera non c'è. Cipolla in frigo prima di tagliarla, o lama bagnata: il gas si scioglie nell'acqua.</p>` },

porro:{ nome:"Porro", match:["porr"], ricette:["porr"],
 cons:{verde:[["Carota","mosca del porro e della carota si confondono a vicenda"],["Sedano","tradizionalmente insieme"],["Lattuga e valerianella","tra le file"],["Cipolla","stesse esigenze"],["Fragola","funghi"]],giallo:[],rosso:[["Fagiolo, pisello, fava","rallenta i legumi"]]},
 conserva:`<p>In campo tutto l'inverno, coperto di paglia: regge −15. In cantina con le radici nella sabbia 2 mesi. A rondelle congelato crudo (per vellutate e soffritti). Il porro è la pianta più facile da conservare: la conserva è il campo.</p>`, storia:`` },

mais:{ nome:"Mais dolce e popcorn", match:["mais","popcorn","pannocch"], ricette:["mais","pannocch","polenta"],
 cons:{verde:[["Fagiolo rampicante","gli sale sopra e gli dà azoto"],["Zucca e zucchina","coprono il terreno"],["Cetriolo e melone","tutore"],["Pisello","azoto"]],giallo:[["Patata","ok ma competono per l'azoto"]],rosso:[["Pomodoro","nottua in comune"],["Sedano","acqua"]]},
 conserva:`<p>Mais dolce: chicchi tagliati dalla pannocchia e congelati entro poche ore (lo zucchero diventa amido in un giorno). Popcorn e mais da polenta: pannocchie lasciate seccare sulla pianta, poi appese al coperto un mese, sgranate quando i chicchi si staccano da soli; in barattolo di vetro durano anni. Il popcorn scoppia solo con il 13–14% di umidità: se non scoppia, è troppo secco (aggiungi un cucchiaio d'acqua nel barattolo per un giorno).</p>`, storia:`` },

girasole:{ nome:"Girasole", match:["girasol"], ricette:["girasole"],
 cons:{verde:[["Cetriolo","tutore e ombra"],["Mais","stessi tempi"]],giallo:[["Fagiolo","va se il girasole è basso"]],rosso:[["Patata","inibisce i tuberi"],["Pomodoro","competizione"]]},
 conserva:`<p>Capolini raccolti quando il retro ingiallisce, seccati al coperto, semi sgranati: tostati con sale, o per gli uccelli d'inverno. I semi germogliano in vaschetta in gennaio come microgreens.</p>`, storia:`` },

basilico:{ nome:"Basilico e aromatiche estive", match:["basilic","aromatic","salvia","rosmarin","timo","origan","menta","dragoncell","santoreggia","cumino","stevia","verbena","lavanda"], ricette:["basilico","pesto","erbe"],
 cons:{verde:[["Pomodoro","la coppia classica"],["Peperone e melanzana","afidi"],["Zucchina","impollinatori"]],giallo:[["Cetriolo","ok ma le aromatiche forti lo rallentano"]],rosso:[["Rucola","competizione"],["Salvia con cetriolo e cipolla","incompatibili"]]},
 conserva:`<p>Basilico: pesto congelato in vaschette da ghiaccio; foglie intere in olio in congelatore; sale aromatizzato. Non essiccare il basilico (perde tutto). Origano, timo, salvia, rosmarino, menta, santoreggia: essiccati in mazzi all'ombra o nell'essiccatoio, sbriciolati in barattolo: durano 1 anno. Verbena odorosa e menta essiccate per la tisana. Stevia: foglie essiccate e polverizzate. Le piante legnose (salvia, rosmarino, timo) svernano fuori; il basilico e la stevia no.</p>`, storia:`` },

prezzemolo:{ nome:"Prezzemolo, cerfoglio, coriandolo, aneto", match:["prezzemol","cerfogli","coriandol","aneto","borragin"], ricette:["prezzemol","salsa verde","erbe"],
 cons:{verde:[["Pomodoro","insetti utili"],["Asparago","classico per il prezzemolo"],["Cavoli","aneto e coriandolo attirano i predatori della cavolaia"],["Cetriolo","aneto"],["Ravanello","cerfoglio"]],giallo:[["Carota","stessa famiglia, stessa mosca"]],rosso:[["Lattuga","prezzemolo e lattuga sono tradizionalmente incompatibili"],["Finocchio e aneto insieme","incrociano"]]},
 conserva:`<p>Prezzemolo: tritato con un filo d'olio in vaschette da ghiaccio congelato; in campo sverna e riparte a marzo. Cerfoglio e aneto: congelati, non essiccati. Coriandolo: le foglie congelate; i semi essiccati sono una spezia. Aneto: i semi per i sottaceti. Borragine: fiori canditi o nel ghiaccio.</p>`, storia:`` },

topinambur:{ nome:"Topinambur, crosne, yacon, batata", match:["topinambur","crosne","yacon","batata"], ricette:["topinambur","yacon","batata","crosne"],
 cons:{verde:[["Fagiolo rampicante","sale sul topinambur"],["Lattuga","ai piedi"]],giallo:[["Zucca","ok a distanza"]],rosso:[["Patata e pomodoro","competizione e per il topinambur invasione"]]},
 conserva:`<p>Topinambur e crosne: in campo, si scavano al bisogno da novembre a marzo (fuori dalla terra durano 1 settimana in frigo). Yacon: in cassetta di sabbia in cantina fino a febbraio, dolcifica con il tempo; le corone si conservano a parte per ripiantare. Batata: dopo la raccolta 10 giorni a 25 °C (curing) poi a 13–15 °C, mai in frigo: fino a marzo.</p>`, storia:`` },

asparago:{ nome:"Asparago", match:["asparag"], ricette:["asparag"],
 cons:{verde:[["Pomodoro","classico: il pomodoro allontana il criocero dell'asparago, l'asparago i nematodi del pomodoro"],["Prezzemolo e basilico","insetti utili"],["Lattuga e spinacio","tra le file in primavera"]],giallo:[],rosso:[["Aglio, cipolla, porro","competizione radicale"],["Patata","scavare rovina le zampe"]]},
 conserva:`<p>Freschi 3 giorni in frigo in piedi in un dito d'acqua. Congelati dopo 2 minuti di sbollentatura. Sott'olio o sottaceto in vasetto. Le punte di luppolo e l'asparago selvatico si conservano allo stesso modo.</p>`, storia:`` },

rabarbaro:{ nome:"Rabarbaro", match:["rabarbar"], ricette:["rabarbar"],
 cons:{verde:[["Cavoli","le foglie di rabarbaro tra i cavoli allontanano la cavolaia"],["Aglio e cipolla","ai piedi"],["Fragola","stesso angolo umido"]],giallo:[],rosso:[["Legumi","competizione"]]},
 conserva:`<p>Coste a pezzi congelate crude. Composta e marmellata in vasetto. Coste sciroppate. Le foglie sono tossiche (acido ossalico): nel compost vanno bene, in cucina no. Il decotto di foglie è un insetticida tradizionale contro gli afidi.</p>`, storia:`` },

cardo:{ nome:"Cardo", match:["cardo"], ricette:["cardo"],
 cons:{verde:[["Fagiolo","azoto"],["Lattuga","ai piedi"]],giallo:[["Carciofo","stessa pianta di fatto"]],rosso:[["Radicchio e lattuga ripetuti","stessa famiglia"]]},
 conserva:`<p>Imbiancato in campo, si raccoglie da novembre a gennaio. Coste pulite, sbollentate in acqua e limone e congelate. Sott'olio dopo cottura. In cantina con le radici e avvolto in carta 2–3 settimane.</p>`, storia:`` },

zafferano:{ nome:"Zafferano", match:["zafferan"], ricette:["zafferan"],
 cons:{verde:[["Lattuga e valerianella","d'inverno tra i bulbi, radici superficiali"],["Aglio","stessi tempi, stesso terreno drenante"]],giallo:[["Fragola","competizione per il drenaggio"]],rosso:[["Tutto ciò che si irriga d'estate","i bulbi in riposo estivo marciscono con l'acqua"]]},
 conserva:`<p>Stimmi staccati il giorno della raccolta, essiccati in 20–30 minuti a 40–45 °C (essiccatoio, forno con lo sportello aperto, vicino alla stufa) fino a diventare fragili. In vasetto di vetro al buio: si usa dopo un mese di riposo e dura 2–3 anni. In fili, mai in polvere (la polvere si taglia). I bulbi si tolgono ogni 3–4 anni a giugno e si ripiantano ad agosto.</p>`,
 storia:`<p>Lo zafferano è una pianta che non esiste in natura. <i>Crocus sativus</i> è sterile, ha tre copie di ogni cromosoma e non fa semi: vive solo perché l'uomo ne ripianta i bulbi da almeno 3.500 anni. Fu selezionato probabilmente a Creta o in Grecia da un croco selvatico, e gli affreschi minoici di Santorini, del 1600 a.C., mostrano ragazze che raccolgono fiori di zafferano e una dea che lo riceve: era già una spezia, un colorante e una medicina. Il nome viene dall'arabo <i>za'faran</i>, "giallo".</p>
<p>Fenici, Greci e Romani lo usarono come profumo, tintura e afrodisiaco: Nerone fece spargere zafferano nelle strade di Roma al suo ingresso, e i Romani se lo mettevano nel vino, nel bagno e sui cuscini dei teatri. Con la fine dell'impero la coltivazione in Italia sparì e la spezia tornò con gli Arabi. La leggenda vuole che un frate domenicano di Navelli, in Abruzzo, tornando dalla Spagna dove era stato inquisitore, portasse i bulbi nel Trecento sull'altopiano dell'Aquila: quello che è certo è che tra Trecento e Cinquecento l'Aquila diventò la capitale europea dello zafferano, con mercanti tedeschi e fiorentini che lo compravano a peso d'oro e lo spedivano a Norimberga e a Venezia. La cultura dello zafferano si estendeva anche alle Marche e all'Umbria, e a Cascia, a un passo dai Sibillini, nel Quattrocento mercanti ebrei vendevano zafferano a Perugia, Spoleto, Civitanova e Camerino. Il prezzo era tale che a Norimberga i falsificatori di zafferano venivano bruciati vivi, e un cavallo si pagava con mezzo chilo di spezia.</p>
<p>Poi, con i secoli, la coltivazione crollò: troppa manodopera per una spezia che il Nord Europa smise di usare. Sopravvisse in Sardegna, a Navelli e a San Gimignano, e negli ultimi vent'anni è tornata: oggi in Italia circa 300 piccole aziende producono 500 chili l'anno, e nel Maceratese ci sono di nuovo campi di croco. Curiosità agronomica: servono circa 150 fiori per un grammo di stimmi secchi, e un chilo vale 15–30.000 euro non per il capriccio del mercato ma perché ogni fiore va raccolto a mano all'alba e "sfiorato" a mano nello stesso giorno. Il fiore vive un giorno. Fiorisce a ottobre-novembre, quando nell'orto è morto tutto, e sotto la neve i bulbi non temono niente: temono solo l'acqua d'estate, quando dormono. Per questo qui vuole l'aiuola rialzata.</p>` },

agretti:{ nome:"Agretti (barba di frate)", match:["agrett"], ricette:["agrett"],
 cons:{verde:[["Lattuga e ravanello","stessi tempi"],["Fragola","copertura"]],giallo:[["Spinacio e bietola","stessa famiglia"]],rosso:[]},
 conserva:`<p>Solo freschi, 2 giorni in frigo in un sacchetto umido. Sott'olio dopo sbollentatura, per chi ne ha tanti. I semi si conservano pochi mesi: quelli dell'anno prima non nascono.</p>`, storia:`` },

fragola:{ nome:"Fragola", match:["fragol"], ricette:["fragol"],
 cons:{verde:[["Aglio e cipolla","funghi e insetti"],["Spinacio e valerianella","coprono il terreno tra le piante"],["Lattuga","stessi tempi"],["Fagiolo nano","azoto"],["Borragine","impollinatori e si dice migliori il sapore"],["Timo","muffa grigia"]],giallo:[["Porro","ok"]],rosso:[["Cavoli","competizione"],["Pomodoro, patata, melanzana","verticillium in comune"]]},
 conserva:`<p>Marmellata (la classica), sciroppo, congelate intere su un vassoio e poi in sacchetto, essiccate a fette nell'essiccatoio (chips). Fresche 2 giorni. Le piante si rinnovano ogni 3 anni con gli stoloni.</p>`, storia:`` },

piccolifrutti:{ nome:"Lamponi, more, ribes, uva spina, mirtillo, goji, aronia, sambuco", match:["lampon","more","ribes","uva spina","mirtill","goji","aronia","sambuc","piccoli frutti"], ricette:["lampon","more","sambuco","ribes"],
 cons:{verde:[["Aglio","ai piedi"],["Tanaceto e aromatiche","insetti"],["Trifoglio come copertura","azoto"]],giallo:[["Fragola","ok se non all'ombra"]],rosso:[["Patata e pomodoro","verticillium per i lamponi"],["More vicino ai lamponi","si passano malattie e si mescolano i polloni"]]},
 conserva:`<p>Congelati su vassoio poi in sacchetto (il metodo migliore per tutti). Marmellate, sciroppi, gelatina di ribes. Aronia e goji essiccati. Fiori di sambuco in sciroppo, bacche cotte in sciroppo (crude sono tossiche). Uva spina in composta.</p>`, storia:`` },

frutta:{ nome:"Alberi da frutto (melo, pero, susino, ciliegio, cotogno, fico, noce, nocciolo, kaki, frutti dimenticati)", match:["alberi","frutt","meli","peri","susin","cilieg","cotogn","fico","fichi","noce","nocciol","kaki","cach","azzeruol","giuggiol","nespol","sorbo","corniol","melogran","kiwi","vite","talee"], ricette:["mele","mela","pere","cachi","noci","fichi","castagn","ciliegie","albicocc","prugne","uva"],
 cons:{verde:[["Aglio, cipolla, erba cipollina ai piedi","afidi e bolla del pesco"],["Nasturzio e tagete","afidi e nematodi"],["Trifoglio, facelia, fiori","impollinatori"],["Lavanda e salvia","carpocapsa"]],giallo:[["Orto sotto la chioma","ombra e competizione: solo insalate a primavera"]],rosso:[["Noce sopra l'orto","le foglie e le radici del noce rilasciano juglone che inibisce pomodori, patate, peperoni"],["Erba alta al piede","competizione per l'acqua nei primi 3 anni"]]},
 conserva:`<p>Mele e pere da conservazione: in cassette in cantina fresca e umida, non a contatto, controllate ogni 2 settimane: fino a marzo. Cotogne: cotognata e gelatina. Noci: sgusciate o intere in luogo asciutto, 1 anno. Castagne: 9 giorni in acqua ("novena") poi asciutte, o congelate sbucciate. Cachi: maturano in casa con le mele. Fichi: secchi al sole o nell'essiccatoio. Susine e albicocche: marmellata e secche. Ciliegie: sciroppate e sotto spirito.</p>`, storia:`` },

physalis:{ nome:"Physalis e tomatillo", match:["physalis","alchecheng","tomatillo"], ricette:["physalis","tomatillo"],
 cons:{verde:[["Basilico","afidi"],["Carota","non compete"],["Tagete","nematodi"]],giallo:[["Pomodoro e peperone","stessa famiglia"]],rosso:[["Patata","malattie"]]},
 conserva:`<p>Physalis: nel loro cartoccio in luogo fresco e asciutto durano 2–3 mesi; marmellata; essiccati. Tomatillo: nel cartoccio in frigo 3 settimane; salsa verde in vasetto sterilizzato o congelata; interi congelati.</p>`, storia:`` },

okra:{ nome:"Okra, luffa, lagenaria", match:["okra","luffa","lagenaria"], ricette:["okra"],
 cons:{verde:[["Peperone e melanzana","stesse esigenze di caldo"],["Basilico","afidi"],["Lattuga","ombra"]],giallo:[["Zucca","ok"]],rosso:[["Patata","competizione"]]},
 conserva:`<p>Okra: sottaceto, o congelata dopo sbollentatura; essiccata a fette. Luffa: lasciata seccare sulla pianta, sbucciata, lavata, sbiancata in acqua e candeggina: spugna per anni. Lagenaria: appesa a seccare 6 mesi in luogo ventilato, poi svuotata: contenitore o mestolo per sempre.</p>`, storia:`` },

quinoa:{ nome:"Quinoa, amaranto, grano saraceno, sovescio", match:["quinoa","amarant","saraceno","sovescio","segale","veccia","favino"], ricette:["quinoa","amaranto","saraceno"],
 cons:{verde:[["Fagiolo","azoto"],["Mais","stessa altezza per l'amaranto"]],giallo:[["Bietola e spinacio","stessa famiglia per la quinoa"]],rosso:[]},
 conserva:`<p>Semi sgranati dalle pannocchie secche, ventilati, essiccati 2 settimane, in barattolo. La quinoa va lavata bene prima di cuocere (saponine amare). Il grano saraceno si decortica male in casa: meglio macinarlo in farina con la buccia per le crespelle. L'amaranto si soffia in padella come il popcorn.</p>`, storia:`` },

fiori:{ nome:"Fiori utili e commestibili (tagete, calendula, nasturzio, borragine, cosmos, zinnia)", match:["tagete","calendul","nasturz","cosmos","zinnia","fiordalis","crocus","tulipan","narcis","fiori"], ricette:["fiori"],
 cons:{verde:[["Tutto l'orto","tagete contro i nematodi, calendula e borragine per le api, nasturzio come esca per gli afidi, cosmos e zinnia per i sirfidi"]],giallo:[],rosso:[["Nasturzio troppo vicino alle insalate","attira gli afidi che poi passano"]]},
 conserva:`<p>Calendula: petali essiccati per tisane e oleolito (in olio d'oliva 40 giorni al sole: la crema per le mani). Nasturzio: boccioli sottaceto come capperi. Borragine: fiori nel ghiaccio. Tagete: fiori essiccati contro le tarme. Semi di tutti raccolti a settembre per l'anno dopo.</p>`, storia:`` },

funghi:{ nome:"Funghi su tronco", match:["fungh","shiitake","pleurotus"], ricette:["fungh"],
 cons:{verde:[["Angolo ombroso sotto gli alberi","umidità"]],giallo:[],rosso:[["Sole e vento","seccano i tronchi"]]},
 conserva:`<p>Shiitake e pleurotus essiccati a fette nell'essiccatoio (lo shiitake secco è meglio del fresco): in barattolo 1 anno. Sott'olio dopo sbollentatura in acqua e aceto. Congelati dopo cottura in padella.</p>`, storia:`` },

luppolo:{ nome:"Luppolo", match:["luppol"], ricette:["luppolo"],
 cons:{verde:[["Recinzione o pergola","gli serve un supporto da 5–6 metri"],["Fagiolo","stesso tutore"]],giallo:[],rosso:[["Tutto ciò che sta sotto","ombra totale in estate"]]},
 conserva:`<p>Coni raccolti a settembre quando sono cartacei e profumano, essiccati a 40 °C, sottovuoto o in sacchetto nel congelatore per la birra: 1 anno. Germogli di primavera solo freschi. Cuscino di luppolo secco: il sonnifero della nonna.</p>`, storia:`` },

liquirizia:{ nome:"Liquirizia e stevia", match:["liquiriz"], ricette:["liquirizia"],
 cons:{verde:[["Angolo a sé","radici invasive"]],giallo:[],rosso:[["Orto vicino","le radici della liquirizia vanno ovunque"]]},
 conserva:`<p>Radici scavate dal terzo anno a novembre, lavate, tagliate a bastoncini ed essiccate: si masticano o si fa il decotto. Estratto: radici bollite a lungo e il liquido ridotto a pasta.</p>`, storia:`` }
,
germogli:{ nome:"Germogli e microgreens", match:["germogli","microgreen"], ricette:["germogli"],
 cons:{verde:[["Cucina","si fanno in vaschetta sul davanzale, non nell'orto"]],giallo:[],rosso:[]},
 conserva:`<p>Germogli in barattolo (lenticchie, ceci, ravanello, alfalfa): sciacquati due volte al giorno, pronti in 3–5 giorni, in frigo 3 giorni. Microgreens su terriccio (piselli, girasole, ravanello, crescione): tagliati con le forbici a 7–10 giorni, non ricrescono, in frigo 4 giorni. Non si conservano oltre: si fa una vaschetta nuova ogni settimana.</p>`, storia:`` },
forzature:{ nome:"Forzature in cantina (witloof, radicchio tardivo, rabarbaro)", match:["forzatur"], ricette:["witloof","radicchio","rabarbaro"],
 cons:{verde:[["Cantina buia e fresca (8–15 °C)","è tutto ciò che serve"]],giallo:[],rosso:[["Luce","rende amari i cespi e verdi le coste"]]},
 conserva:`<p>Le radici di witloof e radicchio si conservano in sabbia in cantina e si forzano poche alla volta, ogni 3 settimane, per avere cespi freschi fino a marzo. I cespi forzati durano una settimana in frigo. Il rabarbaro forzato sotto il secchio si raccoglie per 4–6 settimane, poi la pianta va lasciata riposare un anno.</p>`, storia:`` }
};
